import type { JsonSchema, JsonSchemaNode } from '../contracts/json-schema.ts'
import type { Diagnostic } from '../errors/zen-error.ts'
import { Codes } from '../errors/codes.ts'
import { resolveRef } from './json-schema.ts'

/**
 * What a response schema itself says must not be returned — rfcs/0001 §13.3,
 * §16.2.
 *
 * §13.3's guarantee is that an *undeclared* field cannot be emitted. A
 * *declared* one that its own schema marks "never returned" could be, until
 * `0.1.0-alpha.4`: `password: z.string().meta({ writeOnly: true })` in a
 * response schema went out on the wire, while the configuration store has read
 * that same keyword as a secret marker since §16 landed. Zen's flagship
 * guarantee covered every field except the ones a schema had flagged.
 *
 * So the response schema is walked the way the serializer IR walks it — every
 * position a response can carry: properties, an `additionalProperties` schema,
 * array items, tuple positions, every branch of a union, through `$ref`s — and
 * two markers are reported with their JSON path:
 *
 *   - **`writeOnly: true`** — JSON Schema's "may be sent, never returned". A
 *     **boot error**: there is no reading of it under which returning the
 *     field is right.
 *   - **`format: 'password'`** — OpenAPI's "do not display". A **warning**: it
 *     is weaker than "never returned", and a hash may carry it on purpose.
 *
 * Keywords that constrain validity without describing what is emitted (`not`,
 * `if`/`then`, `contains`) are not walked, for the serializer's reason: they
 * are not positions a response carries. The plain form, every negotiated JSON
 * representation and every schema handed to a media encoder go through this,
 * so a CSV export cannot carry a field the JSON one may not (§13.4.4).
 *
 * The first slice of field clearance — which declared fields a caller may
 * receive — and it costs nothing per request: it runs at boot and changes no
 * generated byte.
 */
export interface ExposureFinding {
  readonly path: string
  readonly marker: 'writeOnly' | 'password'
}

export function neverReturned(schema: JsonSchema): readonly ExposureFinding[] {
  const findings: ExposureFinding[] = []
  const reported = new Set<string>()
  const active = new Set<string>()

  const visit = (node: JsonSchemaNode | undefined, path: string): void => {
    if (typeof node !== 'object' || node === null) return

    const marker = node['writeOnly'] === true ? 'writeOnly' : node.format === 'password' ? 'password' : null
    if (marker !== null) {
      const key = `${marker} ${path}`
      if (!reported.has(key)) {
        reported.add(key)
        findings.push({ path, marker })
      }
    }

    if (typeof node.$ref === 'string') {
      // Guarded by the descent, not by the location: a recursive component is
      // followed to where it repeats on this path and no further (§29.7's fix).
      const ref = node.$ref
      if (!active.has(ref)) {
        const target = resolveRef(schema, ref)
        if (target !== null) {
          active.add(ref)
          visit(target, path)
          active.delete(ref)
        }
      }
    }

    for (const [key, child] of Object.entries(node.properties ?? {})) visit(child, `${path}.${key}`)
    const extra = node.additionalProperties
    if (typeof extra === 'object' && extra !== null) visit(extra, `${path}[*]`)
    if (Array.isArray(node.prefixItems)) node.prefixItems.forEach((item, i) => { visit(item, `${path}[${i}]`) })
    if (node.items !== undefined && node.items !== false) visit(node.items, `${path}[]`)
    for (const branch of [node.anyOf, node.oneOf, node.allOf]) {
      if (branch !== undefined) for (const member of branch) visit(member, path)
    }
  }

  visit(schema, '$')
  return findings
}

/**
 * The findings as boot diagnostics — an error per `writeOnly`, a warning per
 * `password` — naming the route, the status, the media type and the path.
 */
export function exposureDiagnostics(
  schema: JsonSchema,
  where: { readonly routeId: string; readonly status: number; readonly media: string },
): Diagnostic[] {
  const out: Diagnostic[] = []
  for (const finding of neverReturned(schema)) {
    const location = `${where.routeId} → ${where.status} → ${where.media} → ${finding.path}`
    if (finding.marker === 'writeOnly') {
      out.push({
        severity: 'error',
        code: Codes.RESPONSE_WRITE_ONLY,
        message:
          `${where.routeId} response ${where.status} (${where.media}) would return ${finding.path}, which its ` +
          'schema marks writeOnly: true — "may be sent, never returned".',
        hint:
          'Remove the field from the response schema. writeOnly belongs on what a client sends: give the ' +
          'request its own schema, and the response one without it.',
        consequence:
          'The compiled serializer emits every field a response schema declares, so this one would reach ' +
          'the wire on every response — the field its own schema says must never be returned.',
        locations: [location],
      })
    } else {
      out.push({
        severity: 'warning',
        code: Codes.RESPONSE_WRITE_ONLY,
        message:
          `${where.routeId} response ${where.status} (${where.media}) returns ${finding.path}, which its ` +
          "schema marks format: 'password' — \"do not display\". It is sent.",
        hint: 'Remove it from the response schema, or mark it writeOnly: true if it must never be returned.',
        locations: [location],
      })
    }
  }
  return out
}
