import type { Reply } from '../contracts/reply.ts'
import type { HookPlan, PipelinePhase } from '../contracts/hook.ts'
import type { TimeoutStage } from '../contracts/deadline.ts'
import { SYNC_MARKER } from '../contracts/middleware.ts'
import { CodeGen, type CodeUnit } from './codegen.ts'
import {
  attachNegotiated, attachSerializer, finalize, payloadOf, replacePayload, NO_PAYLOAD,
} from '../runtime/response-engine.ts'
import { abandoned } from '../runtime/deadline.ts'
import type { Deadline } from '../runtime/deadline.ts'
import type { SerializerTable } from './serializer.ts'

export type SyncClass = 'sync' | 'async' | 'maybe'

export interface PipelineStep {
  readonly kind: 'phase' | 'around' | 'after'
  readonly name: string
  readonly fn: Function
}

export interface PipelineSpec {
  readonly routeId: string
  readonly steps: readonly PipelineStep[]
  readonly handler: Function
  /** Emitted only when the route declares a body — §4.2 stage 6. */
  readonly intake: ((ctx: unknown) => Promise<void>) | null
  /** One entry per declared source, in the fixed order of §4.2 stage 7. */
  readonly validators: readonly ValidatorStep[]
  /**
   * Status → compiled serializer, for the statuses the route declares. The
   * status is a runtime value, so this stays a table rather than one function.
   */
  readonly serialize: SerializerTable | null
  /**
   * The negotiation step, on routes that declare more than one representation —
   * §13.4. `null` on every other route, which is what the zero-cost gate checks.
   *
   * A function rather than the plan, for the same reason `intake` is a function
   * rather than a body-parser registry: what the pipeline needs to emit is one
   * call, and everything about *how* the choice is made was decided at boot.
   *
   * Its presence also changes how the epilogue binds the response contract —
   * `attachNegotiated` instead of `attachSerializer` — so this field is read
   * twice by the generator and never at request time.
   */
  readonly negotiate?: ((ctx: unknown) => void) | null | undefined
  /**
   * The route's resolved hooks, per phase (§9). Absent means "none anywhere",
   * which is the same thing as every list being empty: no code is emitted.
   *
   * `onParse` is present in the plan but not read here — it composes into
   * `intake`, because a parse hook on a route that declares no body has no
   * stage to run in and must not resurrect one (§9.2).
   */
  readonly hooks?: HookPlan | undefined
  /**
   * Whether this route carries a deadline (§4.4).
   *
   * A boolean, not a duration: *how long* is the dispatcher's business, because
   * the budget can be shortened per request by an inbound header and the
   * pipeline is compiled once. All the pipeline needs to know is whether to
   * emit the stage marks and the abort checks at all — and on a route with no
   * deadline it emits neither, which is the same zero-cost rule the hook system
   * follows (§9.4) and is asserted the same way, against the generated bytes.
   */
  readonly deadline?: boolean | undefined
}

export interface ValidatorStep {
  readonly source: string
  readonly run: (ctx: unknown) => void | Promise<void>
}

export type CompiledPipeline = (ctx: unknown) => Reply | Promise<Reply>

const EMPTY: readonly Function[] = Object.freeze([])

export const NO_HOOKS: HookPlan = Object.freeze({
  onRequest: EMPTY,
  onRoute: EMPTY,
  onParse: EMPTY,
  preValidation: EMPTY,
  postValidation: EMPTY,
  preHandler: EMPTY,
  postHandler: EMPTY,
  onSerialize: EMPTY,
  onSend: EMPTY,
})

/**
 * Classification drives the sync fast path — rfcs/0001 §8.4.
 *
 * A pipeline whose every member is `sync` compiles to a *non-async* function:
 * no promise is allocated for the entire request.
 *
 * A plain function classifies as `maybe`, not `sync` — it could still return a
 * thenable, and guessing otherwise would be unsound. `maybe` therefore forces
 * the async form in 0.1; opting a genuinely synchronous middleware in is one
 * call to `markSync()`. Inferring `maybe` into the sync path needs full CPS
 * emission and is deferred.
 */
export function classifySync(fn: Function): SyncClass {
  if ((fn as unknown as Record<symbol, unknown>)[SYNC_MARKER] === true) return 'sync'
  if (fn.constructor?.name === 'AsyncFunction') return 'async'
  return 'maybe'
}

export function markSync<F extends Function>(fn: F): F {
  Object.defineProperty(fn, SYNC_MARKER, { value: true, enumerable: false })
  return fn
}

interface Deps {
  finalize: typeof finalize
  attachSerializer: typeof attachSerializer
  attachNegotiated: typeof attachNegotiated
  payloadOf: typeof payloadOf
  replacePayload: typeof replacePayload
  NO_PAYLOAD: typeof NO_PAYLOAD
  abandoned: typeof abandoned
  steps: Function[]
  handler: Function
  intake: ((ctx: unknown) => Promise<void>) | null
  validators: Array<(ctx: unknown) => void | Promise<void>>
  serialize: SerializerTable | null
  negotiate: ((ctx: unknown) => void) | null
  hooks: HookPlan
}

/** What the emitted stage checks read off the context. */
interface DeadlineCarrier {
  $deadline: Deadline | null
}

/**
 * The Pipeline Compiler — rfcs/0001 §8.3 and §9.4.
 *
 * Flattens the chain into a *single generated function* per route:
 *
 *   - No array iteration. A 6-middleware route has 6 call sites, not a loop.
 *   - No dynamic dispatch. Steps are direct references V8 can inline.
 *   - Absent stages vanish. No body declared → no intake call exists in the
 *     emitted source at all. Not a runtime `if`; the branch is not generated.
 *   - Short-circuit is a `return`, not an exception or a mutated sentinel.
 *
 * Hooks obey the same rule, which is the load-bearing half of §9.4: a phase
 * with no hooks contributes **no source text**. An application that registers
 * nothing for `onRoute` does not pay an empty array, a `length` check, or a
 * property load for the phase's existence — unlike every framework that keeps
 * hook arrays and walks them per request. The cost of the hook system is
 * exactly the cost of the hooks you wrote.
 *
 * Two contracts this must honour, both verified against `simplePipeline` by the
 * differential suite (§20.5):
 *
 *   1. `around` is **positional**: it wraps only the steps that follow it, in
 *      registration order — the behaviour shown in §8.3's worked example.
 *   2. `after` middleware runs **even when an earlier step short-circuits**
 *      (§8.2), because response logging and transformation must observe
 *      short-circuited replies too.
 */
export function compilePipeline(spec: PipelineSpec, codegen: CodeGen): CompiledPipeline {
  const deps: Deps = {
    finalize,
    attachSerializer,
    attachNegotiated,
    payloadOf,
    replacePayload,
    NO_PAYLOAD,
    abandoned,
    steps: spec.steps.map((s) => s.fn),
    handler: spec.handler,
    intake: spec.intake,
    validators: spec.validators.map((v) => v.run),
    serialize: spec.serialize,
    negotiate: spec.negotiate ?? null,
    hooks: spec.hooks ?? NO_HOOKS,
  }

  const unit: CodeUnit = {
    name: `pipeline:${spec.routeId}`,
    source: generate(spec, codegen.readable),
    externals: { d: deps },
  }

  return codegen.materialise<CompiledPipeline>(unit, () => simplePipeline(spec))
}

function generate(spec: PipelineSpec, readable: boolean): string {
  const hooks = spec.hooks ?? NO_HOOKS
  const decls: string[] = []
  let segmentCount = 0
  const note = (text: string) => (readable ? `  // ${text}\n` : '')

  // `after` steps are hoisted out of the flow: they always run after the
  // handler (or after a short-circuit), in registration order, wherever they
  // were registered. Walking them positionally caused the compiler to silently
  // drop any phase step that followed an `after`.
  const flow: Array<{ step: PipelineStep; index: number }> = []
  const afters: Array<{ step: PipelineStep; index: number }> = []
  spec.steps.forEach((step, index) => {
    if (step.kind === 'after') afters.push({ step, index })
    else flow.push({ step, index })
  })

  /**
   * A hook chain that may short-circuit: `onRequest`, `onRoute`,
   * `preValidation`, `postValidation`, `preHandler`, `postHandler`.
   *
   * Identical in shape to a phase-middleware call site, on purpose — a hook is
   * not a second, slower dispatch mechanism, it is the same one with a
   * lifecycle position attached.
   */
  const emitGuards = (
    phase: PipelinePhase,
    lines: string[],
    finishWith: (expr: string) => string,
    extraArg = '',
  ): boolean => {
    let needsAsync = false
    const list = hooks[phase]
    for (let i = 0; i < list.length; i++) {
      const cls = classifySync(list[i] as Function)
      const call = `d.hooks.${phase}[${i}](ctx${extraArg})`
      lines.push(note(`${phase}[${i}] [${cls}]`))
      if (cls === 'sync') {
        lines.push(`  r = ${call}; if (r !== undefined) ${finishWith('d.finalize(r, true)')}`)
      } else if (cls === 'async') {
        needsAsync = true
        lines.push(`  r = await ${call}; if (r !== undefined) ${finishWith('d.finalize(r, true)')}`)
      } else {
        needsAsync = true
        lines.push(
          `  r = ${call}; if (r !== null && typeof r === 'object' && typeof r.then === 'function') r = await r`,
          `  if (r !== undefined) ${finishWith('d.finalize(r, true)')}`,
        )
      }
    }
    return needsAsync
  }

  /**
   * A stage boundary, for routes that declared a deadline — §4.4, §4.1.
   *
   * Two facts and two branches: record which region of the pipeline we are
   * entering, then stop if this request is already over. The mark is what lets
   * a blown deadline report "the handler stage", and it is a store of an
   * interned literal; the check reads a plain boolean rather than
   * `signal.aborted`, which is a native accessor called three times a request.
   *
   * `d.abandoned()` deliberately skips the epilogue. `after` middleware is
   * application logic and §4.6 keeps that off the failure path, and the
   * transform hooks have nothing left to transform. `onResponse` still fires,
   * from the dispatcher — that phase's whole contract is that it sees
   * everything, and abandoned requests are the ones most worth counting.
   *
   * The granularity is the *stage*, not the step. A check between every
   * middleware would cost a branch per step on every deadline-bearing route to
   * win only where several consecutive steps are each slow, which is not the
   * shape of a real chain; the four boundaries of §4.1 are where the time
   * actually goes.
   */
  const emitBoundary = (stage: TimeoutStage, lines: string[]): void => {
    if (spec.deadline !== true) return
    lines.push(note(`deadline: entering ${stage}`))
    lines.push(
      `  { const dl = ctx.$deadline` +
      `; if (dl !== null) { dl.stage = '${stage}'; if (dl.done) return d.abandoned() } }`,
    )
  }

  // ── the epilogue: after middleware → onSerialize → onSend → contract ───────
  //
  // Ordering here is the mirror of the entry (§9.3), and the response contract
  // is attached *last* on purpose: §13.3's guarantee then covers whatever is
  // actually being sent — including short-circuited replies and anything a hook
  // substituted — rather than only what the handler first produced. The
  // consequence is worth stating because it is a security property, not a
  // detail: an `onSerialize` hook **cannot smuggle an undeclared field past the
  // response schema**, because the serializer runs after it.
  const negotiates = (spec.negotiate ?? null) !== null

  const hasEpilogue =
    afters.length > 0 ||
    spec.serialize !== null ||
    negotiates ||
    hooks.onSerialize.length > 0 ||
    hooks.onSend.length > 0

  let epilogueAsync = afters.some(({ step }) => classifySync(step.fn) !== 'sync')

  if (hasEpilogue) {
    const lines: string[] = []

    for (const { step, index } of afters) {
      const cls = classifySync(step.fn)
      const call = `d.steps[${index}](ctx, reply)`
      lines.push(cls === 'sync'
        ? `${note(`after: ${step.name} [sync]`)}  reply = ${call}`
        : `${note(`after: ${step.name} [${cls}]`)}  { const ar = ${call}; reply = (ar !== null && typeof ar === 'object' && typeof ar.then === 'function') ? await ar : ar }`)
    }

    // `onSerialize` sees the *payload*, not the reply, and only when there is
    // one to see: a stream, a file or a 204 has no value to transform, so the
    // whole block is guarded once rather than each hook re-deriving it.
    if (hooks.onSerialize.length > 0) {
      lines.push(note('onSerialize: payload transform (json/text bodies only)'))
      lines.push('  { let p = d.payloadOf(reply)')
      lines.push('    if (p !== d.NO_PAYLOAD) {')
      for (let i = 0; i < hooks.onSerialize.length; i++) {
        const cls = classifySync(hooks.onSerialize[i] as Function)
        if (cls === 'sync') {
          lines.push(`      { const t = d.hooks.onSerialize[${i}](ctx, p); if (t !== undefined) p = t }`)
        } else {
          epilogueAsync = true
          lines.push(
            `      { let t = d.hooks.onSerialize[${i}](ctx, p)`,
            "        if (t !== null && typeof t === 'object' && typeof t.then === 'function') t = await t",
            '        if (t !== undefined) p = t }',
          )
        }
      }
      lines.push('      reply = d.replacePayload(reply, p) } }')
    }

    // `onSend` sees the whole reply. Returning nothing means "unchanged", so a
    // header-stamping hook is one line and cannot accidentally erase the body
    // by forgetting to return it.
    for (let i = 0; i < hooks.onSend.length; i++) {
      const cls = classifySync(hooks.onSend[i] as Function)
      lines.push(note(`onSend[${i}] [${cls}]`))
      if (cls === 'sync') {
        lines.push(`  { const sr = d.hooks.onSend[${i}](ctx, reply); if (sr !== undefined) reply = sr }`)
      } else {
        epilogueAsync = true
        lines.push(
          `  { let sr = d.hooks.onSend[${i}](ctx, reply)`,
          "    if (sr !== null && typeof sr === 'object' && typeof sr.then === 'function') sr = await sr",
          '    if (sr !== undefined) reply = sr }',
        )
      }
    }

    // §13.4 — a negotiated route binds through the two-table form, which knows
    // the difference between a status the route negotiates and one it does not.
    // A route that declares no variant form emits the line it always emitted,
    // byte for byte, which is what `benchmarks/negotiation` gates on.
    if (negotiates) {
      lines.push(note('serialize: the negotiated representation, then the plain contracts'))
      lines.push('  reply = d.attachNegotiated(ctx, reply, d.serialize)')
    } else if (spec.serialize !== null) {
      lines.push(note('serialize: compiled from the route response schema'))
      lines.push('  reply = d.attachSerializer(ctx, reply, d.serialize)')
    }

    decls.push(buildFn('finish', `${lines.join('\n')}\n  return reply`, epilogueAsync, 'ctx, reply'))
  }

  /** Terminate a segment: run the epilogue, bind the contract, return. */
  const finishWith = (valueExpr: string): string =>
    hasEpilogue ? `return finish(ctx, ${valueExpr})` : `return ${valueExpr}`

  function emitSegment(from: number): string {
    const name = `seg${segmentCount++}`
    const lines: string[] = []
    let needsAsync = epilogueAsync

    // ── stage 5: onRequest, then onRoute ──────────────────────────────────
    // Both precede application middleware, which is what makes them the right
    // place for auth, CORS and rate limiting: refusing here means never having
    // read the body of a request you were going to reject.
    if (from === 0) {
      if (emitGuards('onRequest', lines, finishWith)) needsAsync = true
      if (emitGuards('onRoute', lines, finishWith, ', ctx.route')) needsAsync = true

      // ── §13.4: content negotiation ──────────────────────────────────────
      //
      // After the hooks — a rate-limited or unauthenticated request should not
      // pay for it — and before application middleware, intake and validation,
      // because a 406 is knowable from one header and the frozen graph, and
      // discovering it after a database round trip makes the refusal cost more
      // than the success. It also means `ctx.negotiated` is set before *any*
      // application code runs, so an `around` middleware can use it as a cache
      // key (`runtime/negotiation.ts` has the full argument).
      //
      // Synchronous and unconditional: no `await`, no branch, and on a route
      // that declares one representation, no line.
      if (negotiates) {
        lines.push(note('negotiate: Accept → representation, or 406'))
        lines.push('  d.negotiate(ctx)')
      }
    }

    for (let f = from; f < flow.length; f++) {
      const { step, index } = flow[f] as { step: PipelineStep; index: number }

      if (step.kind === 'around') {
        // The only per-request closure in the design, and only on routes that
        // actually use `around` (§8.2).
        const inner = emitSegment(f + 1)
        lines.push(note(`around: ${step.name}`))
        lines.push(`  return d.steps[${index}](ctx, function () { return ${inner}(ctx) })`)
        decls.push(buildFn(name, `  let r\n${lines.join('\n')}`, true))
        return name
      }

      const cls = classifySync(step.fn)
      lines.push(note(`phase: ${step.name} [${cls}]`))
      if (cls === 'sync') {
        lines.push(`  r = d.steps[${index}](ctx); if (r !== undefined) ${finishWith('d.finalize(r, true)')}`)
      } else if (cls === 'async') {
        needsAsync = true
        lines.push(`  r = await d.steps[${index}](ctx); if (r !== undefined) ${finishWith('d.finalize(r, true)')}`)
      } else {
        needsAsync = true
        lines.push(
          `  r = d.steps[${index}](ctx); if (r !== null && typeof r === 'object' && typeof r.then === 'function') r = await r`,
          `  if (r !== undefined) ${finishWith('d.finalize(r, true)')}`,
        )
      }
    }

    // ── stage 6: intake (emitted only when the route declares a body) ──────
    if (spec.intake !== null) {
      needsAsync = true
      emitBoundary('intake', lines)
      lines.push(note('intake: read + parse body' + (hooks.onParse.length > 0 ? ' (onParse hooks composed in)' : '')))
      lines.push('  await d.intake(ctx)')
    }

    // ── stage 7: validation, in the fixed order of §4.2 ────────────────────
    emitBoundary('validate', lines)
    if (emitGuards('preValidation', lines, finishWith)) needsAsync = true

    for (let v = 0; v < spec.validators.length; v++) {
      const validator = spec.validators[v] as ValidatorStep
      const cls = classifySync(validator.run)
      lines.push(note(`validate: ${validator.source} [${cls}]`))
      if (cls === 'sync') {
        lines.push(`  d.validators[${v}](ctx)`)
      } else {
        needsAsync = true
        lines.push(`  { const vr = d.validators[${v}](ctx); if (vr !== undefined && typeof vr.then === 'function') await vr }`)
      }
    }

    if (emitGuards('postValidation', lines, finishWith)) needsAsync = true

    // ── stage 8: handler ──────────────────────────────────────────────────
    emitBoundary('handler', lines)
    if (emitGuards('preHandler', lines, finishWith)) needsAsync = true

    const handlerClass = classifySync(spec.handler)
    lines.push(note(`handler [${handlerClass}]`))
    if (handlerClass === 'sync') {
      lines.push('  let out = d.handler(ctx)')
    } else if (handlerClass === 'async') {
      needsAsync = true
      lines.push('  let out = await d.handler(ctx)')
    } else {
      needsAsync = true
      lines.push(
        '  let out = d.handler(ctx)',
        '  if (out !== null && typeof out === "object" && typeof out.then === "function") out = await out',
      )
    }

    // `postHandler` sees what the handler returned, before it becomes a Reply,
    // which is what makes it usable for caching and enveloping decisions that
    // need the domain value rather than the transport wrapper.
    if (emitGuards('postHandler', lines, finishWith, ', out')) needsAsync = true

    lines.push('  let reply = d.finalize(out, false)')
    lines.push(`  ${finishWith('reply')}`)

    decls.push(buildFn(name, `  let r\n${lines.join('\n')}`, needsAsync))
    return name
  }

  const entry = emitSegment(0)
  return `${decls.join('\n\n')}\n\nreturn ${entry}`
}

function buildFn(name: string, body: string, isAsync: boolean, params = 'ctx'): string {
  return `${isAsync ? 'async ' : ''}function ${name}(${params}) {\n${body}\n}`
}

/**
 * `SimplePipeline` — the interpreted twin (§8.4, I6).
 *
 * Straightforward, always-async, no codegen. This is the *semantic definition*
 * of a Zen pipeline; `compilePipeline` must match it exactly, and the
 * differential fuzzer asserts that on random chains — now including random hook
 * placements, which is how the two forms of "does a short-circuit still run the
 * epilogue" stay in agreement. Users select it in one line
 * (`pipeline: 'simple'`) if they ever suspect the compiler.
 *
 * It walks the step list positionally for the same reason the compiler does: an
 * `around` registered third must wrap what comes after it, not the whole chain.
 */
export function simplePipeline(spec: PipelineSpec): CompiledPipeline {
  const hooks = spec.hooks ?? NO_HOOKS
  const flow = spec.steps.filter((s) => s.kind !== 'after')
  const afters = spec.steps.filter((s) => s.kind === 'after')

  const finish = async (ctx: unknown, reply: Reply): Promise<Reply> => {
    let current = reply
    for (const step of afters) {
      current = await (step.fn as (c: unknown, r: Reply) => Reply | Promise<Reply>)(ctx, current)
    }

    if (hooks.onSerialize.length > 0) {
      let payload = payloadOf(current)
      if (payload !== NO_PAYLOAD) {
        for (const hook of hooks.onSerialize) {
          const next = await (hook as (c: unknown, p: unknown) => unknown)(ctx, payload)
          if (next !== undefined) payload = next
        }
        current = replacePayload(current, payload)
      }
    }

    for (const hook of hooks.onSend) {
      const next = await (hook as (c: unknown, r: Reply) => Reply | void)(ctx, current)
      if (next !== undefined) current = next
    }

    if ((spec.negotiate ?? null) !== null) {
      return attachNegotiated(ctx as never, current, spec.serialize)
    }
    return spec.serialize === null
      ? current
      : attachSerializer(ctx as { $resStatus: number }, current, spec.serialize)
  }

  /**
   * Returns a Reply when a hook short-circuited, `null` to keep going.
   *
   * `extra` is an array rather than an optional value because `postHandler`'s
   * second argument is the handler's return value, which is legitimately
   * `undefined` on a 204 — so "no second argument" and "a second argument that
   * is undefined" must stay distinguishable, or the twin would diverge from the
   * compiler on exactly the case nobody tests by hand.
   */
  const guards = async (ctx: unknown, phase: PipelinePhase, extra: readonly unknown[] = []): Promise<Reply | null> => {
    for (const hook of hooks[phase]) {
      const result = await (hook as (...args: unknown[]) => unknown)(ctx, ...extra)
      if (result !== undefined) return finalize(result, true)
    }
    return null
  }

  /** The twin of `emitBoundary`. Same two facts, same skipped epilogue. */
  const boundary = (ctx: unknown, stage: TimeoutStage): Reply | null => {
    if (spec.deadline !== true) return null
    const dl = (ctx as DeadlineCarrier).$deadline
    if (dl === null) return null
    dl.stage = stage
    return dl.done ? abandoned() : null
  }

  const runFrom = async (ctx: unknown, from: number): Promise<Reply> => {
    if (from === 0) {
      const early = await guards(ctx, 'onRequest')
      if (early !== null) return finish(ctx, early)
      const routed = await guards(ctx, 'onRoute', [(ctx as { route: unknown }).route])
      if (routed !== null) return finish(ctx, routed)
      // §13.4, in the same position the compiler emits it. A 406 throws from
      // here and takes the error path, exactly as it does in the compiled form.
      spec.negotiate?.(ctx)
    }

    for (let i = from; i < flow.length; i++) {
      const step = flow[i] as PipelineStep

      if (step.kind === 'around') {
        const fn = step.fn as (c: unknown, n: () => Promise<Reply>) => Promise<Reply>
        return fn(ctx, () => runFrom(ctx, i + 1))
      }

      const r = await (step.fn as (c: unknown) => unknown)(ctx)
      if (r !== undefined) return finish(ctx, finalize(r, true))
    }

    if (spec.intake !== null) {
      const stopped = boundary(ctx, 'intake')
      if (stopped !== null) return stopped
      await spec.intake(ctx)
    }

    const atValidate = boundary(ctx, 'validate')
    if (atValidate !== null) return atValidate

    const prev = await guards(ctx, 'preValidation')
    if (prev !== null) return finish(ctx, prev)

    for (const validator of spec.validators) await validator.run(ctx)

    const postv = await guards(ctx, 'postValidation')
    if (postv !== null) return finish(ctx, postv)

    const atHandler = boundary(ctx, 'handler')
    if (atHandler !== null) return atHandler

    const preh = await guards(ctx, 'preHandler')
    if (preh !== null) return finish(ctx, preh)

    const out = await (spec.handler as (c: unknown) => unknown)(ctx)

    const posth = await guards(ctx, 'postHandler', [out])
    if (posth !== null) return finish(ctx, posth)

    return finish(ctx, finalize(out, false))
  }

  return (ctx: unknown) => runFrom(ctx, 0)
}
