import type { Reply } from '../contracts/reply.ts'
import type { HookPlan, PipelinePhase } from '../contracts/hook.ts'
import type { TimeoutStage } from '../contracts/deadline.ts'
import { SYNC_MARKER } from '../contracts/middleware.ts'
import { CodeGen, type CodeUnit } from './codegen.ts'
import {
  attachNegotiated, attachSerializer, finalize, payloadOf, replacePayload, NO_PAYLOAD,
} from '../runtime/response-engine.ts'
import { abandoned } from '../runtime/deadline.ts'
import type { Deadline } from '../runtime/deadline.ts'
import type { SerializerTable } from './serializer.ts'

export type SyncClass = 'sync' | 'async' | 'maybe'

export interface PipelineStep {
  readonly kind: 'phase' | 'around' | 'after'
  readonly name: string
  readonly fn: Function
}

export interface PipelineSpec {
  readonly routeId: string
  readonly steps: readonly PipelineStep[]
  readonly handler: Function
  /** Emitted only when the route declares a body — §4.2 stage 6. */
  readonly intake: ((ctx: unknown) => Promise<void>) | null
  /** One entry per declared source, in the fixed order of §4.2 stage 7. */
  readonly validators: readonly ValidatorStep[]
  /**
   * Status → compiled serializer, for the statuses the route declares. The
   * status is a runtime value, so this stays a table rather than one function.
   */
  readonly serialize: SerializerTable | null
  /**
   * The negotiation step, on routes that declare more than one representation —
   * §13.4. `null` on every other route, which is what the zero-cost gate checks.
   *
   * A function rather than the plan, for the same reason `intake` is a function
   * rather than a body-parser registry: what the pipeline needs to emit is one
   * call, and everything about *how* the choice is made was decided at boot.
   *
   * Its presence also changes how the epilogue binds the response contract —
   * `attachNegotiated` instead of `attachSerializer` — so this field is read
   * twice by the generator and never at request time.
   */
  readonly negotiate?: ((ctx: unknown) => void) | null | undefined
  /**
   * The route's resolved hooks, per phase (§9). Absent means "none anywhere",
   * which is the same thing as every list being empty: no code is emitted.
   *
   * `onParse` is present in the plan but not read here — it composes into
   * `intake`, because a parse hook on a route that declares no body has no
   * stage to run in and must not resurrect one (§9.2).
   */
  readonly hooks?: HookPlan | undefined
  /**
   * Whether this route carries a deadline (§4.4).
   *
   * A boolean, not a duration: *how long* is the dispatcher's business, because
   * the budget can be shortened per request by an inbound header and the
   * pipeline is compiled once. All the pipeline needs to know is whether to
   * emit the stage marks and the abort checks at all — and on a route with no
   * deadline it emits neither, which is the same zero-cost rule the hook system
   * follows (§9.4) and is asserted the same way, against the generated bytes.
   */
  readonly deadline?: boolean | undefined
}

export interface ValidatorStep {
  readonly source: string
  readonly run: (ctx: unknown) => void | Promise<void>
}

export type CompiledPipeline = (ctx: unknown) => Reply | Promise<Reply>

const EMPTY: readonly Function[] = Object.freeze([])

export const NO_HOOKS: HookPlan = Object.freeze({
  onRequest: EMPTY,
  onRoute: EMPTY,
  onParse: EMPTY,
  preValidation: EMPTY,
  postValidation: EMPTY,
  preHandler: EMPTY,
  postHandler: EMPTY,
  onSerialize: EMPTY,
  onSend: EMPTY,
})

/**
 * Classification drives the sync fast path — rfcs/0001 §8.4.
 *
 * A pipeline whose every member is `sync` compiles to a *non-async* function:
 * no promise is allocated for the entire request.
 *
 * A plain function classifies as `maybe`, not `sync` — it could still return a
 * thenable, and guessing otherwise would be unsound. A `maybe` call site is a
 * *speculation point*: the call is made synchronously, and only if it returns
 * a thenable does the rest of the request wait for it (see {@link Chain}). So a
 * route of plain functions that return values runs synchronously end to end,
 * and one that returns a promise somewhere pays for that promise there. An
 * `async` function always returns a promise, so a route holding one keeps the
 * `async` form, as does a route with a body, whose intake is a read.
 * `markSync()` still declares a function synchronous outright, which saves the
 * thenable check at its call site.
 */
export function classifySync(fn: Function): SyncClass {
  if ((fn as unknown as Record<symbol, unknown>)[SYNC_MARKER] === true) return 'sync'
  if (fn.constructor?.name === 'AsyncFunction') return 'async'
  return 'maybe'
}

export function markSync<F extends Function>(fn: F): F {
  Object.defineProperty(fn, SYNC_MARKER, { value: true, enumerable: false })
  return fn
}

/**
 * The most speculation points one chain of generated functions may hold —
 * §8.4's bound on the synchronous stack.
 *
 * A request that passes a speculation point synchronously goes one call deeper,
 * because the rest of the chain is the next function. Past this many, a chain
 * keeps the `async` form, where each `await` returns to the event loop instead.
 * Real chains hold a handful; the bound is for the pathological ones.
 */
export const MAX_SPECULATION = 32

/** What a run of call sites compiles to: a plain function, a chain of continuations, or an `async` function. */
type Shape = 'sync' | 'speculative' | 'async'

function shapeOf(classes: readonly SyncClass[], alwaysAsync: boolean): Shape {
  if (alwaysAsync || classes.includes('async')) return 'async'
  let maybe = 0
  for (const cls of classes) if (cls === 'maybe') maybe++
  if (maybe === 0) return 'sync'
  return maybe > MAX_SPECULATION ? 'async' : 'speculative'
}

/** What decides a route's sync path — the inputs the compiler classifies, and nothing else. */
export interface SyncPathInput {
  readonly steps: readonly PipelineStep[]
  readonly hooks: HookPlan
  readonly handler: Function
  /** The route declares a body: intake is a read, so the request always waits once. */
  readonly intake: boolean
  /** Validator call sites — plain functions the compiler built, one per route that validates anything. */
  readonly validators: number
}

/**
 * Whether a request on this route can finish without a promise, and if not,
 * what makes it wait — the line `explainRoute` prints (§8.4, the sync-path
 * advisor).
 *
 * Classified by the rules {@link compilePipeline} emits from, over the same
 * inputs, so the line cannot describe a pipeline other than the one that runs.
 * It describes the compiled pipeline: `pipeline: 'simple'` and `caps.eval ===
 * false` run the interpreted twin, which is always asynchronous.
 */
export function describeSyncPath(input: SyncPathInput): string {
  const afters = input.steps.filter((s) => s.kind === 'after')
  const flow = input.steps.filter((s) => s.kind !== 'after')
  const waits: string[] = []
  let synchronous = 0
  // The bound applies per chain, as the compiler applies it: the epilogue is
  // one chain and the segment the handler runs in is another.
  const maybes = { epilogue: 0, segment: 0 }
  const count = (cls: SyncClass, label: string, chain: 'epilogue' | 'segment'): void => {
    if (cls === 'async') waits.push(`${label} (async function)`)
    else if (cls === 'maybe') maybes[chain]++
    else synchronous++
  }

  for (const step of afters) count(classifySync(step.fn), `after ${step.name}`, 'epilogue')
  input.hooks.onSerialize.forEach((hook, i) => count(classifySync(hook), `onSerialize[${i}]`, 'epilogue'))
  input.hooks.onSend.forEach((hook, i) => count(classifySync(hook), `onSend[${i}]`, 'epilogue'))

  for (const phase of ['onRequest', 'onRoute', 'preValidation', 'postValidation', 'preHandler', 'postHandler'] as const) {
    input.hooks[phase].forEach((hook, i) => count(classifySync(hook), `${phase}[${i}]`, 'segment'))
  }
  const arounds = flow.filter((s) => s.kind === 'around').map((s) => `around ${s.name}`)
  for (const step of flow) if (step.kind !== 'around') count(classifySync(step.fn), step.name, 'segment')
  maybes.segment += input.validators
  count(classifySync(input.handler), 'the handler', 'segment')

  if (input.intake) waits.unshift('the body is read')
  // `next()` is a promise: a route that wraps never finishes without one.
  waits.push(...arounds)
  for (const chain of ['segment', 'epilogue'] as const) {
    if (maybes[chain] > MAX_SPECULATION) {
      waits.push(`${maybes[chain]} plain functions in the ${chain === 'segment' ? 'request' : 'epilogue'}, past the ${MAX_SPECULATION} one synchronous chain may hold`)
    }
  }

  if (waits.length > 0) return `always async — ${waits.join(', ')}`
  const speculative = maybes.segment + maybes.epilogue
  if (speculative === 0) return 'synchronous — every call is marked synchronous; no promise is allocated'
  return `no promise unless a call returns one — ${speculative} ${speculative === 1 ? 'call' : 'calls'} speculated` +
    (synchronous > 0 ? `, ${synchronous} marked synchronous` : '')
}

/** The thenable test the compiler has always emitted for a value a call returned. */
const thenable = (name: string): string =>
  `${name} !== null && typeof ${name} === 'object' && typeof ${name}.then === 'function'`

/**
 * Generated functions that continue one another — the speculative form of
 * rfcs/0001 §8.4, whose table specifies it as `r = mw(ctx); if (isThenable(r))
 * return r.then(k)`.
 *
 * A speculation point ends the function it is in. If the call returned a
 * thenable, the rest runs once it settles — adopted through `Promise.resolve`,
 * exactly as `await` adopts it, so a foreign thenable is treated the way it
 * always was. Any other value is handed to the rest directly. The rest is the
 * next function, written once, so the code grows with the number of call sites
 * rather than doubling at each one — and a request whose calls all return
 * values runs synchronously from start to finish without allocating a promise.
 *
 * Three things hold by construction, and the differential suite holds them
 * against `simplePipeline`:
 *
 *   - **A throw stays where it was.** A synchronous throw propagates
 *     synchronously, and the dispatcher already calls the pipeline inside its
 *     `try`; a rejection propagates through the returned promise.
 *   - **Nothing moves.** Stage marks, deadline checks and the epilogue sit
 *     exactly where the `async` form puts them; a continuation begins where an
 *     `await` would have resumed.
 *   - **The stack is bounded**, by {@link MAX_SPECULATION}.
 */
class Chain {
  readonly #out: string[]
  readonly #counter: { n: number }
  readonly #prelude: string
  #head: string
  #lines: string[] = []

  /**
   * `out` receives each finished function; `counter` numbers continuations
   * across the whole unit, so their names cannot collide; `prelude` opens every
   * function of the chain (`let r`, for the code that assigns it).
   */
  constructor(out: string[], counter: { n: number }, head: string, prelude: string) {
    this.#out = out
    this.#counter = counter
    this.#head = head
    this.#prelude = prelude
  }

  /** One line of the current function. `note()` text is '' outside readable mode, and ends in a newline inside it. */
  line(text: string): void {
    if (text === '') return
    this.#lines.push(text.endsWith('\n') ? text.slice(0, -1) : text)
  }

  /** The name of a continuation that has not been started yet — for a jump forward. */
  label(): string {
    return `k${++this.#counter.n}`
  }

  /**
   * A speculation point: evaluate `call` into `name`, and continue in a new
   * function whose parameters are `ctx`, then `carry` — what the rest still
   * reads — then, unless `result` is `null`, the value under the name `result`.
   */
  speculate(call: string, name: string, test: string, carry: readonly string[], result: string | null): void {
    const next = this.label()
    const passed = result === null ? [] : [name]
    this.#lines.push(`  const ${name} = ${call}`)
    this.#lines.push(
      `  if (${test}) return Promise.resolve(${name}).then((${result === null ? '' : 'v'}) => ` +
      `${next}(${['ctx', ...carry, ...(result === null ? [] : ['v'])].join(', ')}))`,
    )
    this.#lines.push(`  return ${next}(${['ctx', ...carry, ...passed].join(', ')})`)
    this.#begin(`${next}(${['ctx', ...carry, ...(result === null ? [] : [result])].join(', ')})`)
  }

  /** Continue, unconditionally, in the function `label` names — a jump forward over a block. */
  goto(label: string, carry: readonly string[]): void {
    this.#lines.push(`  return ${label}(${['ctx', ...carry].join(', ')})`)
    this.#begin(`${label}(${['ctx', ...carry].join(', ')})`)
  }

  end(): void {
    this.#out.push(`function ${this.#head} {\n${this.#prelude}${this.#lines.join('\n')}\n}`)
  }

  #begin(head: string): void {
    this.end()
    this.#head = head
    this.#lines = []
  }
}

interface Deps {
  finalize: typeof finalize
  attachSerializer: typeof attachSerializer
  attachNegotiated: typeof attachNegotiated
  payloadOf: typeof payloadOf
  replacePayload: typeof replacePayload
  NO_PAYLOAD: typeof NO_PAYLOAD
  abandoned: typeof abandoned
  steps: Function[]
  handler: Function
  intake: ((ctx: unknown) => Promise<void>) | null
  validators: Array<(ctx: unknown) => void | Promise<void>>
  serialize: SerializerTable | null
  negotiate: ((ctx: unknown) => void) | null
  hooks: HookPlan
}

/** What the emitted stage checks read off the context. */
interface DeadlineCarrier {
  $deadline: Deadline | null
}

/**
 * The Pipeline Compiler — rfcs/0001 §8.3 and §9.4.
 *
 * Flattens the chain into a *single generated function* per route:
 *
 *   - No array iteration. A 6-middleware route has 6 call sites, not a loop.
 *   - No dynamic dispatch. Steps are direct references V8 can inline.
 *   - Absent stages vanish. No body declared → no intake call exists in the
 *     emitted source at all. Not a runtime `if`; the branch is not generated.
 *   - Short-circuit is a `return`, not an exception or a mutated sentinel.
 *
 * Hooks obey the same rule, which is the load-bearing half of §9.4: a phase
 * with no hooks contributes **no source text**. An application that registers
 * nothing for `onRoute` does not pay an empty array, a `length` check, or a
 * property load for the phase's existence — unlike every framework that keeps
 * hook arrays and walks them per request. The cost of the hook system is
 * exactly the cost of the hooks you wrote.
 *
 * Two contracts this must honour, both verified against `simplePipeline` by the
 * differential suite (§20.5):
 *
 *   1. `around` is **positional**: it wraps only the steps that follow it, in
 *      registration order — the behaviour shown in §8.3's worked example.
 *   2. `after` middleware runs **even when an earlier step short-circuits**
 *      (§8.2), because response logging and transformation must observe
 *      short-circuited replies too.
 */
export function compilePipeline(spec: PipelineSpec, codegen: CodeGen): CompiledPipeline {
  const deps: Deps = {
    finalize,
    attachSerializer,
    attachNegotiated,
    payloadOf,
    replacePayload,
    NO_PAYLOAD,
    abandoned,
    steps: spec.steps.map((s) => s.fn),
    handler: spec.handler,
    intake: spec.intake,
    validators: spec.validators.map((v) => v.run),
    serialize: spec.serialize,
    negotiate: spec.negotiate ?? null,
    hooks: spec.hooks ?? NO_HOOKS,
  }

  const unit: CodeUnit = {
    name: `pipeline:${spec.routeId}`,
    source: generate(spec, codegen.readable),
    externals: { d: deps },
  }

  return codegen.materialise<CompiledPipeline>(unit, () => simplePipeline(spec))
}

function generate(spec: PipelineSpec, readable: boolean): string {
  const hooks = spec.hooks ?? NO_HOOKS
  const decls: string[] = []
  let segmentCount = 0
  const note = (text: string) => (readable ? `  // ${text}\n` : '')

  // `after` steps are hoisted out of the flow: they always run after the
  // handler (or after a short-circuit), in registration order, wherever they
  // were registered. Walking them positionally caused the compiler to silently
  // drop any phase step that followed an `after`.
  const flow: Array<{ step: PipelineStep; index: number }> = []
  const afters: Array<{ step: PipelineStep; index: number }> = []
  spec.steps.forEach((step, index) => {
    if (step.kind === 'after') afters.push({ step, index })
    else flow.push({ step, index })
  })

  /**
   * A hook chain that may short-circuit: `onRequest`, `onRoute`,
   * `preValidation`, `postValidation`, `preHandler`, `postHandler`.
   *
   * Identical in shape to a phase-middleware call site, on purpose — a hook is
   * not a second, slower dispatch mechanism, it is the same one with a
   * lifecycle position attached.
   */
  const emitGuards = (
    phase: PipelinePhase,
    lines: string[],
    finishWith: (expr: string) => string,
    extraArg = '',
  ): boolean => {
    let needsAsync = false
    const list = hooks[phase]
    for (let i = 0; i < list.length; i++) {
      const cls = classifySync(list[i] as Function)
      const call = `d.hooks.${phase}[${i}](ctx${extraArg})`
      lines.push(note(`${phase}[${i}] [${cls}]`))
      if (cls === 'sync') {
        lines.push(`  r = ${call}; if (r !== undefined) ${finishWith('d.finalize(r, true)')}`)
      } else if (cls === 'async') {
        needsAsync = true
        lines.push(`  r = await ${call}; if (r !== undefined) ${finishWith('d.finalize(r, true)')}`)
      } else {
        needsAsync = true
        lines.push(
          `  r = ${call}; if (r !== null && typeof r === 'object' && typeof r.then === 'function') r = await r`,
          `  if (r !== undefined) ${finishWith('d.finalize(r, true)')}`,
        )
      }
    }
    return needsAsync
  }

  /**
   * A stage boundary, for routes that declared a deadline — §4.4, §4.1.
   *
   * Two facts and two branches: record which region of the pipeline we are
   * entering, then stop if this request is already over. The mark is what lets
   * a blown deadline report "the handler stage", and it is a store of an
   * interned literal; the check reads a plain boolean rather than
   * `signal.aborted`, which is a native accessor called three times a request.
   *
   * `d.abandoned()` deliberately skips the epilogue. `after` middleware is
   * application logic and §4.6 keeps that off the failure path, and the
   * transform hooks have nothing left to transform. `onResponse` still fires,
   * from the dispatcher — that phase's whole contract is that it sees
   * everything, and abandoned requests are the ones most worth counting.
   *
   * The granularity is the *stage*, not the step. A check between every
   * middleware would cost a branch per step on every deadline-bearing route to
   * win only where several consecutive steps are each slow, which is not the
   * shape of a real chain; the four boundaries of §4.1 are where the time
   * actually goes.
   */
  const emitBoundary = (stage: TimeoutStage, lines: string[]): void => {
    if (spec.deadline !== true) return
    lines.push(note(`deadline: entering ${stage}`))
    lines.push(
      `  { const dl = ctx.$deadline` +
      `; if (dl !== null) { dl.stage = '${stage}'; if (dl.done) return d.abandoned() } }`,
    )
  }

  // ── the epilogue: after middleware → onSerialize → onSend → contract ───────
  //
  // Ordering here is the mirror of the entry (§9.3), and the response contract
  // is attached *last* on purpose: §13.3's guarantee then covers whatever is
  // actually being sent — including short-circuited replies and anything a hook
  // substituted — rather than only what the handler first produced. The
  // consequence is worth stating because it is a security property, not a
  // detail: an `onSerialize` hook **cannot smuggle an undeclared field past the
  // response schema**, because the serializer runs after it.
  const negotiates = (spec.negotiate ?? null) !== null

  const hasEpilogue =
    afters.length > 0 ||
    spec.serialize !== null ||
    negotiates ||
    hooks.onSerialize.length > 0 ||
    hooks.onSend.length > 0

  // Continuations are numbered across the whole unit: every function in it
  // shares one scope.
  const counter = { n: 0 }

  // §8.4 — a speculative epilogue is a chain of continuations, and returns a
  // promise only when one of its members did; any other epilogue is emitted in
  // the form it always had. `epilogueAsync` means "`finish` is an `async`
  // function", which every segment then inherits, as it always did.
  const epilogueShape = shapeOf([
    ...afters.map(({ step }) => classifySync(step.fn)),
    ...hooks.onSerialize.map((hook) => classifySync(hook)),
    ...hooks.onSend.map((hook) => classifySync(hook)),
  ], false)

  let epilogueAsync = afters.some(({ step }) => classifySync(step.fn) !== 'sync')

  if (hasEpilogue && epilogueShape === 'speculative') {
    epilogueAsync = false
    emitSpeculativeEpilogue()
  } else if (hasEpilogue) {
    const lines: string[] = []

    for (const { step, index } of afters) {
      const cls = classifySync(step.fn)
      const call = `d.steps[${index}](ctx, reply)`
      lines.push(cls === 'sync'
        ? `${note(`after: ${step.name} [sync]`)}  reply = ${call}`
        : `${note(`after: ${step.name} [${cls}]`)}  { const ar = ${call}; reply = (ar !== null && typeof ar === 'object' && typeof ar.then === 'function') ? await ar : ar }`)
    }

    // `onSerialize` sees the *payload*, not the reply, and only when there is
    // one to see: a stream, a file or a 204 has no value to transform, so the
    // whole block is guarded once rather than each hook re-deriving it.
    if (hooks.onSerialize.length > 0) {
      lines.push(note('onSerialize: payload transform (json/text bodies only)'))
      lines.push('  { let p = d.payloadOf(reply)')
      lines.push('    if (p !== d.NO_PAYLOAD) {')
      for (let i = 0; i < hooks.onSerialize.length; i++) {
        const cls = classifySync(hooks.onSerialize[i] as Function)
        if (cls === 'sync') {
          lines.push(`      { const t = d.hooks.onSerialize[${i}](ctx, p); if (t !== undefined) p = t }`)
        } else {
          epilogueAsync = true
          lines.push(
            `      { let t = d.hooks.onSerialize[${i}](ctx, p)`,
            "        if (t !== null && typeof t === 'object' && typeof t.then === 'function') t = await t",
            '        if (t !== undefined) p = t }',
          )
        }
      }
      lines.push('      reply = d.replacePayload(reply, p) } }')
    }

    // `onSend` sees the whole reply. Returning nothing means "unchanged", so a
    // header-stamping hook is one line and cannot accidentally erase the body
    // by forgetting to return it.
    for (let i = 0; i < hooks.onSend.length; i++) {
      const cls = classifySync(hooks.onSend[i] as Function)
      lines.push(note(`onSend[${i}] [${cls}]`))
      if (cls === 'sync') {
        lines.push(`  { const sr = d.hooks.onSend[${i}](ctx, reply); if (sr !== undefined) reply = sr }`)
      } else {
        epilogueAsync = true
        lines.push(
          `  { let sr = d.hooks.onSend[${i}](ctx, reply)`,
          "    if (sr !== null && typeof sr === 'object' && typeof sr.then === 'function') sr = await sr",
          '    if (sr !== undefined) reply = sr }',
        )
      }
    }

    // §13.4 — a negotiated route binds through the two-table form, which knows
    // the difference between a status the route negotiates and one it does not.
    // A route that declares no variant form emits the line it always emitted,
    // byte for byte, which is what `benchmarks/negotiation` gates on.
    if (negotiates) {
      lines.push(note('serialize: the negotiated representation, then the plain contracts'))
      lines.push('  reply = d.attachNegotiated(ctx, reply, d.serialize)')
    } else if (spec.serialize !== null) {
      lines.push(note('serialize: compiled from the route response schema'))
      lines.push('  reply = d.attachSerializer(ctx, reply, d.serialize)')
    }

    decls.push(buildFn('finish', `${lines.join('\n')}\n  return reply`, epilogueAsync, 'ctx, reply'))
  }

  /** Terminate a segment: run the epilogue, bind the contract, return. */
  const finishWith = (valueExpr: string): string =>
    hasEpilogue ? `return finish(ctx, ${valueExpr})` : `return ${valueExpr}`

  /** Emit the segment starting at `from`; returns its name and whether it is async. */
  function emitSegment(from: number): { name: string; isAsync: boolean } {
    if (tailShape(from) === 'speculative') return emitSpeculativeSegment(from)

    const name = `seg${segmentCount++}`
    const lines: string[] = []
    let needsAsync = epilogueAsync

    // ── stage 5: onRequest, then onRoute ──────────────────────────────────
    // Both precede application middleware, which is what makes them the right
    // place for auth, CORS and rate limiting: refusing here means never having
    // read the body of a request you were going to reject.
    if (from === 0) {
      if (emitGuards('onRequest', lines, finishWith)) needsAsync = true
      if (emitGuards('onRoute', lines, finishWith, ', ctx.route')) needsAsync = true

      // ── §13.4: content negotiation ──────────────────────────────────────
      //
      // After the hooks — a rate-limited or unauthenticated request should not
      // pay for it — and before application middleware, intake and validation,
      // because a 406 is knowable from one header and the frozen graph, and
      // discovering it after a database round trip makes the refusal cost more
      // than the success. It also means `ctx.negotiated` is set before *any*
      // application code runs, so an `around` middleware can use it as a cache
      // key (`runtime/negotiation.ts` has the full argument).
      //
      // Synchronous and unconditional: no `await`, no branch, and on a route
      // that declares one representation, no line.
      if (negotiates) {
        lines.push(note('negotiate: Accept → representation, or 406'))
        lines.push('  d.negotiate(ctx)')
      }
    }

    for (let f = from; f < flow.length; f++) {
      const { step, index } = flow[f] as { step: PipelineStep; index: number }

      if (step.kind === 'around') {
        // The only per-request closure in the design, and only on routes that
        // actually use `around` (§8.2).
        //
        // `next` is typed `() => Promise<Reply>`, and the segment it calls may
        // be the fully synchronous one §8.4 produces — which returns a bare
        // Reply and throws rather than rejecting. `next().then(…)` then failed
        // with "then is not a function" on exactly the routes that had been
        // optimised, and only there. So a sync segment is called through an
        // `async` wrapper: one promise, on a path that already allocates a
        // closure, and nothing extra when the segment is async already.
        const inner = emitSegment(f + 1)
        const next = inner.isAsync
          ? `function () { return ${inner.name}(ctx) }`
          : `async function () { return ${inner.name}(ctx) }`
        lines.push(note(`around: ${step.name}`))
        lines.push(`  return d.steps[${index}](ctx, ${next})`)
        decls.push(buildFn(name, `  let r\n${lines.join('\n')}`, true))
        return { name, isAsync: true }
      }

      const cls = classifySync(step.fn)
      lines.push(note(`phase: ${step.name} [${cls}]`))
      if (cls === 'sync') {
        lines.push(`  r = d.steps[${index}](ctx); if (r !== undefined) ${finishWith('d.finalize(r, true)')}`)
      } else if (cls === 'async') {
        needsAsync = true
        lines.push(`  r = await d.steps[${index}](ctx); if (r !== undefined) ${finishWith('d.finalize(r, true)')}`)
      } else {
        needsAsync = true
        lines.push(
          `  r = d.steps[${index}](ctx); if (r !== null && typeof r === 'object' && typeof r.then === 'function') r = await r`,
          `  if (r !== undefined) ${finishWith('d.finalize(r, true)')}`,
        )
      }
    }

    // ── stage 6: intake (emitted only when the route declares a body) ──────
    if (spec.intake !== null) {
      needsAsync = true
      emitBoundary('intake', lines)
      lines.push(note('intake: read + parse body' + (hooks.onParse.length > 0 ? ' (onParse hooks composed in)' : '')))
      lines.push('  await d.intake(ctx)')
    }

    // ── stage 7: validation, in the fixed order of §4.2 ────────────────────
    emitBoundary('validate', lines)
    if (emitGuards('preValidation', lines, finishWith)) needsAsync = true

    for (let v = 0; v < spec.validators.length; v++) {
      const validator = spec.validators[v] as ValidatorStep
      const cls = classifySync(validator.run)
      lines.push(note(`validate: ${validator.source} [${cls}]`))
      if (cls === 'sync') {
        lines.push(`  d.validators[${v}](ctx)`)
      } else {
        needsAsync = true
        lines.push(`  { const vr = d.validators[${v}](ctx); if (vr !== undefined && typeof vr.then === 'function') await vr }`)
      }
    }

    if (emitGuards('postValidation', lines, finishWith)) needsAsync = true

    // ── stage 8: handler ──────────────────────────────────────────────────
    emitBoundary('handler', lines)
    if (emitGuards('preHandler', lines, finishWith)) needsAsync = true

    const handlerClass = classifySync(spec.handler)
    lines.push(note(`handler [${handlerClass}]`))
    if (handlerClass === 'sync') {
      lines.push('  let out = d.handler(ctx)')
    } else if (handlerClass === 'async') {
      needsAsync = true
      lines.push('  let out = await d.handler(ctx)')
    } else {
      needsAsync = true
      lines.push(
        '  let out = d.handler(ctx)',
        '  if (out !== null && typeof out === "object" && typeof out.then === "function") out = await out',
      )
    }

    // `postHandler` sees what the handler returned, before it becomes a Reply,
    // which is what makes it usable for caching and enveloping decisions that
    // need the domain value rather than the transport wrapper.
    if (emitGuards('postHandler', lines, finishWith, ', out')) needsAsync = true

    lines.push('  let reply = d.finalize(out, false)')
    lines.push(`  ${finishWith('reply')}`)

    decls.push(buildFn(name, `  let r\n${lines.join('\n')}`, needsAsync))
    return { name, isAsync: needsAsync }
  }

  /**
   * §8.4 — what the segment starting at `from` compiles to, when it is the one
   * the handler runs in. `null` when an `around` comes first: that segment is
   * `async` whatever it holds, as it always has been, because `next()` is a
   * promise and the wrapping already allocates one per request.
   */
  function tailShape(from: number): Shape | null {
    const classes: SyncClass[] = []
    if (from === 0) {
      for (const hook of hooks.onRequest) classes.push(classifySync(hook))
      for (const hook of hooks.onRoute) classes.push(classifySync(hook))
    }
    for (let f = from; f < flow.length; f++) {
      const { step } = flow[f] as { step: PipelineStep; index: number }
      if (step.kind === 'around') return null
      classes.push(classifySync(step.fn))
    }
    for (const phase of ['preValidation', 'postValidation', 'preHandler', 'postHandler'] as const) {
      for (const hook of hooks[phase]) classes.push(classifySync(hook))
    }
    for (const validator of spec.validators) classes.push(classifySync(validator.run))
    classes.push(classifySync(spec.handler))
    // A body is a read, and an `async` epilogue is `await`ed by every segment:
    // either one means the request waits, so the segment keeps its `async` form.
    return shapeOf(classes, spec.intake !== null || epilogueAsync)
  }

  /**
   * The segment the handler runs in, as a chain of continuations — §8.4.
   *
   * The same stages as `emitSegment`, in the same order, with every `maybe`
   * call site a speculation point. It is reached only when nothing in the
   * segment is certain to wait — no `async` member, no body to read, no `async`
   * epilogue — so a request whose plain functions all return values runs it
   * from end to end without allocating a promise.
   */
  function emitSpeculativeSegment(from: number): { name: string; isAsync: boolean } {
    const name = `seg${segmentCount++}`
    const fns: string[] = []
    const chain = new Chain(fns, counter, `${name}(ctx)`, '  let r\n')
    const emitted = (emit: (out: string[]) => void): void => {
      const out: string[] = []
      emit(out)
      for (const line of out) chain.line(line)
    }

    /** A guard hook or a phase step: a value that is not `undefined` answers the request here. */
    const guard = (call: string, cls: SyncClass, label: string, carry: readonly string[]): void => {
      chain.line(note(`${label} [${cls}]`))
      if (cls === 'sync') {
        chain.line(`  r = ${call}; if (r !== undefined) ${finishWith('d.finalize(r, true)')}`)
        return
      }
      const value = `s${counter.n + 1}`
      chain.speculate(call, value, thenable(value), carry, value)
      chain.line(`  if (${value} !== undefined) ${finishWith(`d.finalize(${value}, true)`)}`)
    }
    const guards = (phase: PipelinePhase, args: string, carry: readonly string[]): void => {
      hooks[phase].forEach((hook, i) => guard(`d.hooks.${phase}[${i}](ctx${args})`, classifySync(hook), `${phase}[${i}]`, carry))
    }

    if (from === 0) {
      guards('onRequest', '', [])
      guards('onRoute', ', ctx.route', [])
      if (negotiates) {
        chain.line(note('negotiate: Accept → representation, or 406'))
        chain.line('  d.negotiate(ctx)')
      }
    }

    for (let f = from; f < flow.length; f++) {
      const { step, index } = flow[f] as { step: PipelineStep; index: number }
      guard(`d.steps[${index}](ctx)`, classifySync(step.fn), `phase: ${step.name}`, [])
    }

    emitted((out) => emitBoundary('validate', out))
    guards('preValidation', '', [])
    spec.validators.forEach((validator, v) => {
      const cls = classifySync(validator.run)
      chain.line(note(`validate: ${validator.source} [${cls}]`))
      if (cls === 'sync') {
        chain.line(`  d.validators[${v}](ctx)`)
        return
      }
      const value = `s${counter.n + 1}`
      chain.speculate(`d.validators[${v}](ctx)`, value, `${value} !== undefined && typeof ${value}.then === 'function'`, [], null)
    })
    guards('postValidation', '', [])

    emitted((out) => emitBoundary('handler', out))
    guards('preHandler', '', [])
    const handlerClass = classifySync(spec.handler)
    chain.line(note(`handler [${handlerClass}]`))
    if (handlerClass === 'sync') chain.line('  let out = d.handler(ctx)')
    else chain.speculate('d.handler(ctx)', 'out', thenable('out'), [], 'out')

    guards('postHandler', ', out', ['out'])

    chain.line('  let reply = d.finalize(out, false)')
    chain.line(`  ${finishWith('reply')}`)
    chain.end()
    decls.push(...fns)
    return { name, isAsync: false }
  }

  /**
   * The epilogue as a chain of continuations — §8.4, for an epilogue whose
   * `after` middleware and transform hooks are plain functions. `finish` then
   * returns a promise only when one of them returned one.
   */
  function emitSpeculativeEpilogue(): void {
    const fns: string[] = []
    const chain = new Chain(fns, counter, 'finish(ctx, reply)', '')

    for (const { step, index } of afters) {
      const cls = classifySync(step.fn)
      const call = `d.steps[${index}](ctx, reply)`
      chain.line(note(`after: ${step.name} [${cls}]`))
      if (cls === 'sync') {
        chain.line(`  reply = ${call}`)
        continue
      }
      const value = `s${counter.n + 1}`
      chain.speculate(call, value, thenable(value), [], 'reply')
    }

    if (hooks.onSerialize.length > 0) {
      chain.line(note('onSerialize: payload transform (json/text bodies only)'))
      // A stream, a file or a 204 has no payload to hand a hook, so the hooks
      // are skipped — by a jump over them, since a continuation cannot re-enter
      // the middle of a block.
      const skip = chain.label()
      chain.line('  let p = d.payloadOf(reply)')
      chain.line(`  if (p === d.NO_PAYLOAD) return ${skip}(ctx, reply)`)
      hooks.onSerialize.forEach((hook, i) => {
        const call = `d.hooks.onSerialize[${i}](ctx, p)`
        if (classifySync(hook) === 'sync') {
          chain.line(`  { const t = ${call}; if (t !== undefined) p = t }`)
          return
        }
        const value = `s${counter.n + 1}`
        chain.speculate(call, value, thenable(value), ['reply', 'p'], value)
        chain.line(`  if (${value} !== undefined) p = ${value}`)
      })
      chain.line('  reply = d.replacePayload(reply, p)')
      chain.goto(skip, ['reply'])
    }

    hooks.onSend.forEach((hook, i) => {
      const cls = classifySync(hook)
      const call = `d.hooks.onSend[${i}](ctx, reply)`
      chain.line(note(`onSend[${i}] [${cls}]`))
      if (cls === 'sync') {
        chain.line(`  { const sr = ${call}; if (sr !== undefined) reply = sr }`)
        return
      }
      const value = `s${counter.n + 1}`
      chain.speculate(call, value, thenable(value), ['reply'], value)
      chain.line(`  if (${value} !== undefined) reply = ${value}`)
    })

    if (negotiates) {
      chain.line(note('serialize: the negotiated representation, then the plain contracts'))
      chain.line('  reply = d.attachNegotiated(ctx, reply, d.serialize)')
    } else if (spec.serialize !== null) {
      chain.line(note('serialize: compiled from the route response schema'))
      chain.line('  reply = d.attachSerializer(ctx, reply, d.serialize)')
    }
    chain.line('  return reply')
    chain.end()
    decls.push(...fns)
  }

  const entry = emitSegment(0)
  return `${decls.join('\n\n')}\n\nreturn ${entry.name}`
}

function buildFn(name: string, body: string, isAsync: boolean, params = 'ctx'): string {
  return `${isAsync ? 'async ' : ''}function ${name}(${params}) {\n${body}\n}`
}

/**
 * `SimplePipeline` — the interpreted twin (§8.4, I6).
 *
 * Straightforward, always-async, no codegen. This is the *semantic definition*
 * of a Zen pipeline; `compilePipeline` must match it exactly, and the
 * differential fuzzer asserts that on random chains — now including random hook
 * placements, which is how the two forms of "does a short-circuit still run the
 * epilogue" stay in agreement. Users select it in one line
 * (`pipeline: 'simple'`) if they ever suspect the compiler.
 *
 * It walks the step list positionally for the same reason the compiler does: an
 * `around` registered third must wrap what comes after it, not the whole chain.
 */
export function simplePipeline(spec: PipelineSpec): CompiledPipeline {
  const hooks = spec.hooks ?? NO_HOOKS
  const flow = spec.steps.filter((s) => s.kind !== 'after')
  const afters = spec.steps.filter((s) => s.kind === 'after')

  const finish = async (ctx: unknown, reply: Reply): Promise<Reply> => {
    let current = reply
    for (const step of afters) {
      current = await (step.fn as (c: unknown, r: Reply) => Reply | Promise<Reply>)(ctx, current)
    }

    if (hooks.onSerialize.length > 0) {
      let payload = payloadOf(current)
      if (payload !== NO_PAYLOAD) {
        for (const hook of hooks.onSerialize) {
          const next = await (hook as (c: unknown, p: unknown) => unknown)(ctx, payload)
          if (next !== undefined) payload = next
        }
        current = replacePayload(current, payload)
      }
    }

    for (const hook of hooks.onSend) {
      const next = await (hook as (c: unknown, r: Reply) => Reply | void)(ctx, current)
      if (next !== undefined) current = next
    }

    if ((spec.negotiate ?? null) !== null) {
      return attachNegotiated(ctx as never, current, spec.serialize)
    }
    return spec.serialize === null
      ? current
      : attachSerializer(ctx as { $resStatus: number }, current, spec.serialize)
  }

  /**
   * Returns a Reply when a hook short-circuited, `null` to keep going.
   *
   * `extra` is an array rather than an optional value because `postHandler`'s
   * second argument is the handler's return value, which is legitimately
   * `undefined` on a 204 — so "no second argument" and "a second argument that
   * is undefined" must stay distinguishable, or the twin would diverge from the
   * compiler on exactly the case nobody tests by hand.
   */
  const guards = async (ctx: unknown, phase: PipelinePhase, extra: readonly unknown[] = []): Promise<Reply | null> => {
    for (const hook of hooks[phase]) {
      const result = await (hook as (...args: unknown[]) => unknown)(ctx, ...extra)
      if (result !== undefined) return finalize(result, true)
    }
    return null
  }

  /** The twin of `emitBoundary`. Same two facts, same skipped epilogue. */
  const boundary = (ctx: unknown, stage: TimeoutStage): Reply | null => {
    if (spec.deadline !== true) return null
    const dl = (ctx as DeadlineCarrier).$deadline
    if (dl === null) return null
    dl.stage = stage
    return dl.done ? abandoned() : null
  }

  const runFrom = async (ctx: unknown, from: number): Promise<Reply> => {
    if (from === 0) {
      const early = await guards(ctx, 'onRequest')
      if (early !== null) return finish(ctx, early)
      const routed = await guards(ctx, 'onRoute', [(ctx as { route: unknown }).route])
      if (routed !== null) return finish(ctx, routed)
      // §13.4, in the same position the compiler emits it. A 406 throws from
      // here and takes the error path, exactly as it does in the compiled form.
      spec.negotiate?.(ctx)
    }

    for (let i = from; i < flow.length; i++) {
      const step = flow[i] as PipelineStep

      if (step.kind === 'around') {
        const fn = step.fn as (c: unknown, n: () => Promise<Reply>) => Promise<Reply>
        return fn(ctx, () => runFrom(ctx, i + 1))
      }

      const r = await (step.fn as (c: unknown) => unknown)(ctx)
      if (r !== undefined) return finish(ctx, finalize(r, true))
    }

    if (spec.intake !== null) {
      const stopped = boundary(ctx, 'intake')
      if (stopped !== null) return stopped
      await spec.intake(ctx)
    }

    const atValidate = boundary(ctx, 'validate')
    if (atValidate !== null) return atValidate

    const prev = await guards(ctx, 'preValidation')
    if (prev !== null) return finish(ctx, prev)

    for (const validator of spec.validators) await validator.run(ctx)

    const postv = await guards(ctx, 'postValidation')
    if (postv !== null) return finish(ctx, postv)

    const atHandler = boundary(ctx, 'handler')
    if (atHandler !== null) return atHandler

    const preh = await guards(ctx, 'preHandler')
    if (preh !== null) return finish(ctx, preh)

    const out = await (spec.handler as (c: unknown) => unknown)(ctx)

    const posth = await guards(ctx, 'postHandler', [out])
    if (posth !== null) return finish(ctx, posth)

    return finish(ctx, finalize(out, false))
  }

  return (ctx: unknown) => runFrom(ctx, 0)
}
