import { test, describe, beforeEach } from 'node:test'
import assert from 'node:assert/strict'
import {
  buildCoercePlan, resolveCoercion, planRoute, isInert, compileCoercer, walkCoercer,
  generateCoercerSource, coerceNumber, coerceInteger, coerceBoolean, splitList,
  explainRoute, markSync, CodeGen, DEFAULT_CAPABILITIES, COERCION_DEFAULTS, COERCION_OFF,
  jsonSchema,
  type CoercePlan, type CoercionProfile, type JsonSchema, type RouteRecord,
} from '@erenthedeveloper0/zen-core'
import { makeApp, shaped, silentLogger } from './helpers.ts'

/**
 * Coercion profiles — rfcs/0001 §11.4.
 *
 * The suite is organised around the three rules the design turns on, because
 * each one is a promise that can only be broken silently:
 *
 *   1. a position that accepts a string is never coerced;
 *   2. a value coercion will not convert passes through, and the *schema*
 *      reports it;
 *   3. a route with nothing to convert emits no coercion code at all.
 *
 * The third is checked against the generated bytes rather than a clock, for the
 * reason §9.4 gives: a timing result inside the noise is also what a real small
 * cost looks like.
 */

const codegen = new CodeGen({ caps: DEFAULT_CAPABILITIES })

const profile = (overrides: Partial<CoercionProfile> = {}): CoercionProfile => ({
  ...COERCION_DEFAULTS.query,
  ...overrides,
})

function planOf(json: JsonSchema, overrides: Partial<CoercionProfile> = {}): CoercePlan | null {
  const outcome = buildCoercePlan(shaped(json as Record<string, unknown>), 'query', profile(overrides))
  assert.equal(outcome.kind, 'ok', `expected a plan, got ${outcome.kind}`)
  return outcome.kind === 'ok' ? outcome.plan : null
}

/** Both engines, on the same plan and the same input. Every case runs both. */
function both(plan: CoercePlan, input: Record<string, unknown>): Record<string, unknown> {
  const compiled = compileCoercer(plan, 'test', codegen)
  const walked = walkCoercer(plan)

  const a = compiled({ ...input }) as Record<string, unknown>
  const b = walked({ ...input }) as Record<string, unknown>
  assert.deepEqual(a, b, `compiled and walked coercers diverged\n${generateCoercerSource(plan)}`)
  return a
}

function coerced(json: JsonSchema, input: Record<string, unknown>, overrides: Partial<CoercionProfile> = {}): Record<string, unknown> {
  const plan = planOf(json, overrides)
  return plan === null ? input : both(plan, input)
}

const objectOf = (properties: Record<string, JsonSchema>): JsonSchema => ({ type: 'object', properties })

// ─────────────────────────────────────────────────────────────────────────────

describe('§11.4 rule 1 — a position that accepts a string is never coerced', () => {
  test('a declared string keeps its leading zeros', () => {
    const out = coerced(objectOf({ zip: { type: 'string' } }), { zip: '01234' })
    assert.equal(out['zip'], '01234')
  })

  test('a union of string and number is left as the string it arrived as', () => {
    const json = objectOf({ q: { anyOf: [{ type: 'string' }, { type: 'number' }] } })
    assert.equal(planOf(json), null)
    assert.equal(coerced(json, { q: '5' })['q'], '5')
  })

  test('an unconstrained position is left alone — there is nothing to convert to', () => {
    assert.equal(planOf(objectOf({ anything: {} })), null)
    assert.equal(planOf(objectOf({ anything: true as unknown as JsonSchema })), null)
  })

  test('two different target classes are ambiguous, so neither is chosen', () => {
    const json = objectOf({ flag: { anyOf: [{ type: 'number' }, { type: 'boolean' }] } })
    assert.equal(planOf(json), null, "'1' could be 1 or true and the wire cannot say which")
  })

  test('an object-typed position is not coerced — nested parsing is off (§19.5)', () => {
    assert.equal(planOf(objectOf({ filter: { type: 'object' } })), null)
  })
})

describe('§11.4 rule 2 — coercion proposes, the schema disposes', () => {
  test('a value that will not convert reaches the schema unchanged', () => {
    const out = coerced(objectOf({ page: { type: 'integer' } }), { page: 'banana' })
    assert.equal(out['page'], 'banana')
  })

  test('the empty string is not the number zero', () => {
    // `Number('')` is `0`, which is how `?limit=` becomes a pagination bug that
    // looks like a database bug.
    assert.equal(coerceNumber(''), '')
    assert.equal(coerced(objectOf({ limit: { type: 'integer' } }), { limit: '' })['limit'], '')
  })

  test('hex, Infinity, NaN and separators are not numbers on the wire', () => {
    for (const input of ['0x10', 'Infinity', '-Infinity', 'NaN', '1_000', ' 4', '4 ', '', '.']) {
      assert.equal(coerceNumber(input), input, `${JSON.stringify(input)} should not have converted`)
    }
  })

  test('the decimal grammar that does convert', () => {
    assert.equal(coerceNumber('42'), 42)
    assert.equal(coerceNumber('-3.5'), -3.5)
    assert.equal(coerceNumber('+7'), 7)
    assert.equal(coerceNumber('.5'), 0.5)
    assert.equal(coerceNumber('1e3'), 1000)
    assert.equal(coerceNumber('2.'), 2)
  })

  test('an integer target refuses to lose precision silently', () => {
    // A Postgres bigint id. `Number()` would return …992 and the request would
    // update the wrong row; a 400 is the honest answer.
    assert.equal(coerceInteger('9007199254740993'), '9007199254740993')
    assert.equal(coerceInteger('9007199254740991'), 9007199254740991)
    // A non-integer still converts, because "expected integer, received 3.5" is
    // a better message than "expected integer, received string".
    assert.equal(coerceInteger('3.5'), 3.5)
  })

  test('a float target keeps ordinary float truncation', () => {
    // Floats are understood to be approximate; integer ids are not. The guard
    // is deliberately asymmetric and this pins the asymmetry down.
    assert.equal(coerceNumber('0.12345678901234567'), 0.12345678901234566)
  })

  test('booleans, and the words that are not booleans', () => {
    for (const word of ['true', 'TRUE', '1', 'yes', 'on']) assert.equal(coerceBoolean(word), true)
    for (const word of ['false', 'False', '0', 'no', 'off']) assert.equal(coerceBoolean(word), false)
    for (const word of ['maybe', '', '2', 'truthy']) assert.equal(coerceBoolean(word), word)
  })

  test('custom boolean words replace the defaults', () => {
    const json = objectOf({ on: { type: 'boolean' } })
    const out = coerced(json, { on: 'ja' }, { booleans: { true: ['ja'], false: ['nein'] } })
    assert.equal(out['on'], true)
    assert.equal(coerced(json, { on: 'yes' }, { booleans: { true: ['ja'], false: ['nein'] } })['on'], 'yes')
  })
})

describe('§11.4 — what the declared type asks for', () => {
  test('integer and number are told apart', () => {
    assert.equal(planOf(objectOf({ n: { type: 'integer' } }))?.fields[0]?.op?.kind, 'integer')
    assert.equal(planOf(objectOf({ n: { type: 'number' } }))?.fields[0]?.op?.kind, 'number')
  })

  test('a nullable number still coerces — a query string cannot deliver null', () => {
    const json = objectOf({ n: { anyOf: [{ type: 'number' }, { type: 'null' }] } })
    assert.equal(coerced(json, { n: '4' })['n'], 4)
    assert.equal(coerced(objectOf({ n: { type: 'number', nullable: true } }), { n: '4' })['n'], 4)
  })

  test("a numeric literal coerces — `integer` is a subtype of `number`", () => {
    // `z.literal(7)` converts to `{ type: 'number', const: 7 }`. A plain set
    // intersection makes that uncoercible; JSON Schema's subtype relation does
    // not.
    assert.equal(coerced(objectOf({ v: { type: 'number', const: 7 } }), { v: '7' })['v'], 7)
  })

  test('an enum of numbers coerces; an enum of strings does not', () => {
    assert.equal(coerced(objectOf({ n: { enum: [1, 2, 3] } }), { n: '2' })['n'], 2)
    assert.equal(coerced(objectOf({ s: { enum: ['a', 'b'] } }), { s: 'a' })['s'], 'a')
    assert.equal(planOf(objectOf({ s: { type: 'string', enum: ['a', 'b'] } })), null)
  })

  test('allOf intersects, so a constrained integer is still an integer', () => {
    const json = objectOf({ n: { allOf: [{ type: 'integer' }, { minimum: 1 }] } })
    assert.equal(coerced(json, { n: '5' })['n'], 5)
  })

  test('a $ref is followed', () => {
    const json: JsonSchema = {
      type: 'object',
      properties: { n: { $ref: '#/$defs/Count' } },
      $defs: { Count: { type: 'integer' } },
    }
    assert.equal(coerced(json, { n: '9' })['n'], 9)
  })

  test('a recursive $ref terminates without coercing', () => {
    const json: JsonSchema = {
      type: 'object',
      properties: { node: { $ref: '#/$defs/Node' } },
      $defs: { Node: { anyOf: [{ $ref: '#/$defs/Node' }, { type: 'integer' }] } },
    }
    assert.equal(planOf(json), null)
  })

  test('a $ref at the root of the schema resolves to its object', () => {
    const json: JsonSchema = {
      $ref: '#/$defs/Query',
      $defs: { Query: { type: 'object', properties: { n: { type: 'integer' } } } },
    }
    assert.equal(coerced(json, { n: '3' })['n'], 3)
  })
})

describe('§11.4 — arrays', () => {
  const list = objectOf({ tags: { type: 'array', items: { type: 'string' } } })
  const numbers = objectOf({ ids: { type: 'array', items: { type: 'integer' } } })

  test("`repeat` wraps the single value — the language's most common query bug", () => {
    assert.deepEqual(coerced(list, { tags: 'a' })['tags'], ['a'])
    assert.deepEqual(coerced(list, { tags: ['a', 'b'] })['tags'], ['a', 'b'])
  })

  test('elements are converted after the list is shaped', () => {
    assert.deepEqual(coerced(numbers, { ids: '7' })['ids'], [7])
    assert.deepEqual(coerced(numbers, { ids: ['1', '2'] })['ids'], [1, 2])
  })

  test('`comma` splits, and trims the whitespace RFC 9110 allows', () => {
    assert.deepEqual(coerced(list, { tags: 'a, b ,c' }, { arrays: 'comma' })['tags'], ['a', 'b', 'c'])
    assert.deepEqual(splitList('', ','), [])
    assert.deepEqual(splitList('solo', ','), ['solo'])
  })

  test('`comma` and repetition together keep every value the client sent', () => {
    assert.deepEqual(coerced(list, { tags: ['a,b', 'c'] }, { arrays: 'comma' })['tags'], ['a', 'b', 'c'])
  })

  test('`bracket` reads the alternate key, and only when the plain one is absent', () => {
    const plan = planOf(list, { arrays: 'bracket' })
    assert.equal(plan?.fields[0]?.altKey, 'tags[]')
    assert.deepEqual(both(plan!, { 'tags[]': 'a' })['tags'], ['a'])
    assert.deepEqual(both(plan!, { tags: 'plain', 'tags[]': 'bracketed' })['tags'], ['plain'])
  })

  test('`none` still converts elements — the style shapes the list, not its contents', () => {
    const plan = planOf(numbers, { arrays: 'none' })
    assert.deepEqual(both(plan!, { ids: ['1', '2'] })['ids'], [1, 2])
    assert.equal(both(plan!, { ids: '1' })['ids'], '1', 'a scalar is not wrapped when the style says not to')
  })

  test('an array of strings under `none` has nothing to do, so there is no plan', () => {
    assert.equal(planOf(list, { arrays: 'none' }), null)
  })

  test('a tuple is left alone — per-position types over one list of strings is a guess', () => {
    const json = objectOf({ pair: { type: 'array', prefixItems: [{ type: 'integer' }, { type: 'string' }] } })
    assert.deepEqual(coerced(json, { pair: ['1', 'a'] }, { arrays: 'none' })['pair'], ['1', 'a'])
  })

  test('an array nested in an array compiles two distinct helpers', () => {
    const json = objectOf({ grid: { type: 'array', items: { type: 'array', items: { type: 'integer' } } } })
    const plan = planOf(json)!
    const source = generateCoercerSource(plan)
    assert.match(source, /function a\$0\(/)
    assert.match(source, /function a\$1\(/, 'the inner helper must not reuse the outer name')
    assert.deepEqual(both(plan, { grid: [['1', '2']] })['grid'], [[1, 2]])
  })
})

describe('§11.4 — emptyStringAsUndefined', () => {
  test('off by default: an empty parameter is information', () => {
    assert.equal(coerced(objectOf({ q: { type: 'string' } }), { q: '' })['q'], '')
  })

  test('on, an empty parameter becomes absent so a default can apply', () => {
    const json = objectOf({ q: { type: 'string' } })
    const out = coerced(json, { q: '' }, { emptyStringAsUndefined: true })
    assert.equal(out['q'], undefined)
  })

  test('it applies before conversion, not after', () => {
    const json = objectOf({ n: { type: 'integer' } })
    const out = coerced(json, { n: '' }, { emptyStringAsUndefined: true })
    assert.equal(out['n'], undefined, "'' must not reach the number path")
  })
})

describe('§11.4 — profile resolution down the scope chain', () => {
  test('the defaults are the RFC table', () => {
    assert.equal(COERCION_DEFAULTS.query.numbers, true)
    assert.equal(COERCION_DEFAULTS.query.arrays, 'repeat')
    assert.equal(COERCION_DEFAULTS.headers.arrays, 'comma')
    assert.equal(COERCION_DEFAULTS.headers.numbers, false)
    assert.equal(isInert(COERCION_DEFAULTS.cookies), true)
    assert.equal(isInert(COERCION_DEFAULTS.body), true, 'JSON has real types (§11.4)')
  })

  test('profiles merge field by field, unlike deadlines', () => {
    const resolved = resolveCoercion([
      { query: { numbers: false } },
      { query: { arrays: 'comma' } },
    ])
    assert.equal(resolved.query.numbers, false, 'the outer scope still holds')
    assert.equal(resolved.query.arrays, 'comma', 'and the inner one also holds')
    assert.equal(resolved.query.booleans, true, 'untouched switches keep their default')
  })

  test('`false` at any scope turns everything off, and an inner scope can turn it back on', () => {
    assert.deepEqual(resolveCoercion([false]).query, COERCION_OFF)
    assert.equal(resolveCoercion([false, { query: { numbers: true } }]).query.numbers, true)
  })

  test('`source: false` disables one source only', () => {
    const resolved = resolveCoercion([{ query: false }])
    assert.deepEqual(resolved.query, COERCION_OFF)
    assert.equal(resolved.params.numbers, true)
  })

  test('an explicit undefined does not erase a default', () => {
    // What destructuring an unset config key gives you, under
    // `exactOptionalPropertyTypes`.
    const resolved = resolveCoercion([{ query: { numbers: undefined } }])
    assert.equal(resolved.query.numbers, true)
  })
})

describe('§11.4 — through a real app', () => {
  const query = shaped({
    type: 'object',
    properties: {
      page: { type: 'integer' },
      active: { type: 'boolean' },
      tags: { type: 'array', items: { type: 'string' } },
      zip: { type: 'string' },
    },
  })

  const build = async (opts: Parameters<typeof makeApp>[0] = {}) => {
    const app = makeApp(opts)
    app.get('/search', { query }, (ctx: never) => (ctx as { json(v: unknown): unknown; query: unknown }).json((ctx as { query: unknown }).query))
    await app.ready()
    return app
  }

  test('the types the schema already promised are now the types that arrive', async () => {
    const app = await build()
    const body = (await app.inject('GET', '/search?page=2&active=true&tags=a&zip=01234')).json<Record<string, unknown>>()
    assert.deepEqual(body, { page: 2, active: true, tags: ['a'], zip: '01234' })
  })

  test('a value that will not convert produces the schema\'s own error, not a coercion error', async () => {
    const app = await build()
    const res = await app.inject('GET', '/search?page=banana')
    assert.equal(res.status, 400)
    const problem = res.json<{ code: string; errors: Array<{ path: string[]; message: string }> }>()
    assert.equal(problem.code, 'ZEN_VALIDATION')
    assert.deepEqual(problem.errors[0]?.path, ['page'])
    assert.match(problem.errors[0]?.message ?? '', /expected integer/)
  })

  test('`coercion: false` on the app restores 0.1 behaviour exactly', async () => {
    const app = await build({ coercion: false })
    const body = (await app.inject('GET', '/search?page=2&tags=a')).json<Record<string, unknown>>()
    assert.equal(body['page'], undefined, 'the schema rejected it, so nothing came back')
    assert.equal((await app.inject('GET', '/search?page=2')).status, 400)
  })

  test('a collection profile applies to its subtree, and a route can add to it', async () => {
    const app = makeApp()
    const list = shaped({ type: 'object', properties: { tags: { type: 'array', items: { type: 'string' } } } })
    app.collection('/api', { coercion: { query: { arrays: 'comma' } } }, (c) => {
      c.get('/a', { query: list }, (ctx: never) => (ctx as { json(v: unknown): unknown; query: unknown }).json((ctx as { query: unknown }).query))
      c.get('/b', { query: list, coercion: { query: { arrays: 'repeat' } } }, (ctx: never) => (ctx as { json(v: unknown): unknown; query: unknown }).json((ctx as { query: unknown }).query))
    })
    app.get('/c', { query: list }, (ctx: never) => (ctx as { json(v: unknown): unknown; query: unknown }).json((ctx as { query: unknown }).query))
    await app.ready()

    assert.deepEqual((await app.inject('GET', '/api/a?tags=x,y')).json<{ tags: string[] }>().tags, ['x', 'y'])
    assert.deepEqual((await app.inject('GET', '/api/b?tags=x,y')).json<{ tags: string[] }>().tags, ['x,y'])
    assert.deepEqual((await app.inject('GET', '/c?tags=x,y')).json<{ tags: string[] }>().tags, ['x,y'])
  })

  test('path params are coerced from the schema as well as from `:id<int>`', async () => {
    const app = makeApp()
    app.get('/u/:id', { params: shaped({ type: 'object', properties: { id: { type: 'integer' } } }) },
      (ctx: never) => (ctx as { json(v: unknown): unknown; params: unknown }).json((ctx as { params: unknown }).params))
    await app.ready()
    assert.deepEqual((await app.inject('GET', '/u/42')).json(), { id: 42 })
  })

  test("a typed path param the router already parsed is not re-converted", async () => {
    const app = makeApp()
    app.get('/u/:id<int>', { params: shaped({ type: 'object', properties: { id: { type: 'integer' } } }) },
      (ctx: never) => (ctx as { json(v: unknown): unknown; params: unknown }).json((ctx as { params: unknown }).params))
    await app.ready()
    assert.deepEqual((await app.inject('GET', '/u/42')).json(), { id: 42 })
  })

  test('headers split on commas by default; cookies are untouched', async () => {
    const app = makeApp()
    app.get('/h', {
      headers: shaped({ type: 'object', properties: { 'x-tags': { type: 'array', items: { type: 'string' } } } }),
      cookies: shaped({ type: 'object', properties: { sid: { type: 'string' } } }),
    }, (ctx: never) => (ctx as { json(v: unknown): unknown; headers: unknown }).json((ctx as { headers: unknown }).headers))
    await app.ready()

    const res = await app.inject('GET', '/h', { headers: { 'x-tags': 'a, b', cookie: 'sid=0099' } })
    assert.deepEqual(res.json<{ 'x-tags': string[] }>()['x-tags'], ['a', 'b'])
  })

  test('a JSON body is never coerced — a string age is a client bug, not a convenience', async () => {
    const app = makeApp()
    app.post('/u', { body: shaped({ type: 'object', properties: { age: { type: 'integer' } }, required: ['age'] }) },
      (ctx: never) => (ctx as { json(v: unknown): unknown; body: unknown }).json((ctx as { body: unknown }).body))
    await app.ready()

    const res = await app.inject('POST', '/u', { body: { age: '42' }, headers: { 'content-type': 'application/json' } })
    assert.equal(res.status, 422)
  })

  test('a form body can opt in, because a form is a query string by another name', async () => {
    const app = makeApp({ coercion: { body: { numbers: true, emptyStringAsUndefined: true } } })
    app.post('/u', { body: shaped({ type: 'object', properties: { age: { type: 'integer' }, note: { type: 'string' } } }) },
      (ctx: never) => (ctx as { json(v: unknown): unknown; body: unknown }).json((ctx as { body: unknown }).body))
    await app.ready()

    const res = await app.inject('POST', '/u', {
      body: 'age=42&note=',
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
    })
    assert.deepEqual(res.json(), { age: 42 })
  })

  test('a route that accepts both keeps the JSON guarantee and coerces the form', async () => {
    // The profile is per *source* and the RFC's table is per *media type*, so
    // the content type decides which row applies. A route that takes both would
    // otherwise have to choose between coercing forms and protecting JSON.
    const app = makeApp({ coercion: { body: { numbers: true } } })
    app.post('/u', { body: shaped({ type: 'object', properties: { age: { type: 'integer' } } }) },
      (ctx: never) => (ctx as { json(v: unknown): unknown; body: unknown }).json((ctx as { body: unknown }).body))
    await app.ready()

    const asJson = await app.inject('POST', '/u', { body: { age: '42' }, headers: { 'content-type': 'application/json' } })
    assert.equal(asJson.status, 422, 'JSON has real types; a string age is a client bug')

    const asForm = await app.inject('POST', '/u', {
      body: 'age=42',
      headers: { 'content-type': 'application/x-www-form-urlencoded' },
    })
    assert.deepEqual(asForm.json(), { age: 42 })

    // `application/problem+json` and any other `+json` suffix count as JSON.
    const asProblemJson = await app.inject('POST', '/u', {
      body: { age: '42' },
      headers: { 'content-type': 'application/problem+json' },
    })
    assert.equal(asProblemJson.status, 422)
  })

  test('a text body survives a plan built from an object schema', async () => {
    // The one source that can be something other than an object. A plan derived
    // from `{ type: 'object' }` must not throw when a `text/plain` parser hands
    // it a string.
    const app = makeApp({ coercion: { body: { numbers: true } } })
    app.post('/t', { body: shaped({ type: 'object', properties: { n: { type: 'integer' } } }) },
      (ctx: never) => (ctx as { text(v: string): unknown }).text('ok'))
    await app.ready()
    const res = await app.inject('POST', '/t', { body: 'plain', headers: { 'content-type': 'text/plain' } })
    assert.equal(res.status, 422, 'the schema rejects it; coercion does not crash on it')
  })
})

describe('§11.4 — the zero-cost rule (§9.4, checked against the bytes)', () => {
  test('a route whose schema declares only strings emits no coercer at all', async () => {
    const app = makeApp()
    app.get('/s', { query: shaped({ type: 'object', properties: { q: { type: 'string' } } }) }, markSync(() => ({ ok: true })))
    await app.ready()

    assert.equal(app.generatedSource().filter((u) => u.name.startsWith('coercer:')).length, 0)
    assert.equal(app.graph().routes[0]?.coercion, null)
  })

  test('a route with no schema at all is byte-identical to one compiled before this feature', async () => {
    const bare = makeApp()
    bare.get('/x', markSync(() => ({ ok: true })))
    await bare.ready()

    const withCoercion = makeApp({ coercion: { query: { numbers: true, arrays: 'comma' } } })
    withCoercion.get('/x', markSync(() => ({ ok: true })))
    await withCoercion.ready()

    const pipeline = (a: typeof bare) =>
      a.generatedSource().find((u) => u.name.startsWith('pipeline:'))?.source ?? ''

    assert.notEqual(pipeline(bare), '')
    assert.equal(pipeline(bare), pipeline(withCoercion))
  })

  test('an inert profile never even converts the schema', () => {
    // A schema whose conversion throws. Reaching it at all would mean the
    // profile check ran too late to be a saving.
    let probed = false
    const exploding = {
      '~standard': { version: 1 as const, vendor: 'boom', validate: (value: unknown) => ({ value }) },
      toJSONSchema() { probed = true; throw new Error('nope') },
    } as never

    assert.equal(buildCoercePlan(exploding, 'cookies', COERCION_DEFAULTS.cookies).kind, 'ok')
    assert.equal(probed, false)
  })
})

describe('§11.4 — honesty about what it cannot read', () => {
  let warnings: string[] = []

  beforeEach(() => { warnings = [] })

  const recording = () => {
    const base = silentLogger()
    return { ...base, child: () => recording(), warn: (_meta: unknown, message?: string) => { warnings.push(String(message ?? _meta)) } }
  }

  test('an unconvertible request schema warns once, naming the routes', async () => {
    const app = makeApp({ logger: recording() as never })
    const opaque = {
      '~standard': { version: 1 as const, vendor: 'opaque', validate: (value: unknown) => ({ value }) },
    } as never
    app.get('/a', { query: opaque }, markSync(() => ({ ok: true })))
    app.get('/b', { query: opaque }, markSync(() => ({ ok: true })))
    await app.ready()

    const coercionWarnings = warnings.filter((w) => w.includes('Coercion is enabled'))
    assert.equal(coercionWarnings.length, 1, 'one aggregated warning, not one per route')
    assert.match(coercionWarnings[0] ?? '', /2 request schemas/)
    assert.match(coercionWarnings[0] ?? '', /GET \/a \(query\)/)
    assert.match(coercionWarnings[0] ?? '', /fix: register a converter/)
  })

  test('a schema that is readable but not an object is silent — @erenthedeveloper0/zen-openapi already says so', async () => {
    const app = makeApp({ logger: recording() as never })
    app.get('/a', { query: shaped({ anyOf: [{ type: 'object' }, { type: 'null' }] }) }, markSync(() => ({ ok: true })))
    await app.ready()
    assert.deepEqual(warnings.filter((w) => w.includes('Coercion is enabled')), [])
  })

  test('a describe-only jsonSchema() is still refused as a request schema', async () => {
    // Coercion must not make `jsonSchema()` look usable on a request source:
    // it describes a shape and cannot validate, which is a boot error (§13.3).
    const app = makeApp()
    app.get('/a', { query: jsonSchema({ type: 'object', properties: { n: { type: 'integer' } } }) }, markSync(() => ({ ok: true })))
    await assert.rejects(app.ready(), /jsonSchema\(\)/)
  })
})

describe('§11.4 — the plan is on the graph, so every reader sees the same thing', () => {
  const build = async () => {
    const app = makeApp()
    app.get('/search', {
      query: shaped({
        type: 'object',
        properties: { page: { type: 'integer' }, tags: { type: 'array', items: { type: 'string' } } },
      }),
    }, markSync(() => ({ ok: true })))
    await app.ready()
    return app.graph().routes[0] as RouteRecord
  }

  test('the record carries the derived plan, not the declared profile', async () => {
    const record = await build()
    const plan = record.coercion?.get('query')
    assert.deepEqual(plan?.fields.map((f) => [f.key, f.op?.kind]), [['page', 'integer'], ['tags', 'array']])
  })

  test('explainRoute prints it, above validate, where it runs', async () => {
    const record = await build()
    const explained = explainRoute(record)
    assert.match(explained, /coerce\s+query: page → integer, tags → array of string \(repeat\)/)
    assert.ok(explained.indexOf('coerce') < explained.indexOf('validate'))
  })
})

describe('§11.4 — the interpreted twin is the definition (§14.5, I6)', () => {
  test('caps.eval === false produces the walker, with identical results', async () => {
    const noEval = makeApp({ caps: { ...DEFAULT_CAPABILITIES, eval: false } })
    noEval.get('/s', {
      query: shaped({
        type: 'object',
        properties: { page: { type: 'integer' }, tags: { type: 'array', items: { type: 'integer' } } },
      }),
    }, (ctx: never) => (ctx as { json(v: unknown): unknown; query: unknown }).json((ctx as { query: unknown }).query))
    await noEval.ready()

    const body = (await noEval.inject('GET', '/s?page=2&tags=1&tags=2')).json()
    assert.deepEqual(body, { page: 2, tags: [1, 2] })
  })
})
