import { test, describe, beforeEach } from 'node:test'
import assert from 'node:assert/strict'
import {
  parseAccept, qualityFor, normaliseMediaType, isMediaProblem, isVariantRecord,
  isJsonMedia, wireMediaType, MAX_ACCEPT_RANGES,
  selectOffer, offersOf, makeNegotiator, NEGOTIATION_CACHE_LIMIT,
  registerMediaEncoder, __resetMediaEncoders, jsonSchema, explainRoute,
  NotAcceptable, Codes, jsonReply, replacePayload, encodeBody,
  type Representation,
} from '@erenthedeveloper0/zen-core'
import { makeApp, shaped } from './helpers.ts'

/**
 * Content negotiation — rfcs/0001 §13.4.
 *
 * The suite is organised around the four promises the design makes, because
 * every one of them can be broken silently:
 *
 *   1. **A route that declares one representation is not negotiated**, reads no
 *      `Accept`, stages no `Vary`, and emits no code. Checked against the
 *      generated bytes, for the reason §9.4 gives: a timing result inside the
 *      noise is also what a real small cost looks like.
 *   2. **The most specific matching range decides**, so `text/csv;q=0` plus a
 *      wildcard means "anything but CSV". This is the case implementations get
 *      backwards, and getting it backwards serves a representation the client
 *      explicitly refused.
 *   3. **`Vary: Accept` is on every response**, including the 406 and including
 *      a request that sent no `Accept` at all — the cache-correctness case
 *      §32.2 records for `Vary: Origin`.
 *   4. **A status that is not negotiated keeps its own Content-Type.** A 404
 *      problem document does not become `text/csv` because the client asked for
 *      CSV on the 200.
 */

const CSV = 'text/csv'
const JSON_MEDIA = 'application/json'

const Rows = jsonSchema<Array<{ id: number; email: string }>>({
  type: 'array',
  items: {
    type: 'object',
    properties: { id: { type: 'integer' }, email: { type: 'string' } },
    required: ['id', 'email'],
  },
})

const Problem = jsonSchema<{ code: string }>({
  type: 'object',
  properties: { code: { type: 'string' } },
  required: ['code'],
})

/** A CSV encoder that resolves its columns at boot — the shape §13.4 asks for. */
function csvEncoder(): void {
  registerMediaEncoder(CSV, (schema) => {
    const items = schema?.['items'] as Record<string, unknown> | undefined
    const columns = Object.keys((items?.['properties'] ?? {}) as Record<string, unknown>)
    return (value) => {
      const rows = (Array.isArray(value) ? value : [value]) as Array<Record<string, unknown>>
      return [columns.join(','), ...rows.map((r) => columns.map((c) => String(r[c] ?? '')).join(','))].join('\n')
    }
  })
}

beforeEach(() => {
  // Encoders are process-global (§13.4), and a suite that shares them across
  // tests passes or fails depending on the order the runner picks — the same
  // trap `packages/middleware/test/pack.test.ts` records for the rate limiter.
  __resetMediaEncoders()
  csvEncoder()
})

// ─────────────────────────────────────────────────────────────────────────────

describe('Accept parsing (§13.4)', () => {
  test('an absent, empty or unparseable header is the same thing: nothing', () => {
    assert.equal(parseAccept(undefined), null)
    assert.equal(parseAccept(''), null)
    assert.equal(parseAccept('   '), null)
    assert.equal(parseAccept('garbage'), null, 'no slash, so no range')
    assert.equal(parseAccept(',,,'), null)
  })

  test('a malformed range is skipped, and the readable ones still count', () => {
    const ranges = parseAccept('text/csv, garbage, application/json;q=0.5')
    assert.notEqual(ranges, null)
    assert.equal(ranges!.length, 2)
    assert.deepEqual(ranges!.map((r) => `${r.type}/${r.sub}@${r.q}`), ['text/csv@1', 'application/json@0.5'])
  })

  test('quality defaults to 1, clamps to [0,1], and survives a typo', () => {
    const q = (header: string): number => (parseAccept(header) as ReadonlyArray<{ q: number }>)[0]!.q
    assert.equal(q('text/csv'), 1)
    assert.equal(q('text/csv;q=0.25'), 0.25)
    assert.equal(q('text/csv;q=0'), 0)
    assert.equal(q('text/csv;q=9'), 1, 'clamped')
    assert.equal(q('text/csv;q=-3'), 0, 'clamped')
    assert.equal(q('text/csv;q=banana'), 1, 'a typo means "I want this", not "I refuse it"')
    assert.equal(q('text/csv;Q=0.5'), 0.5, 'parameter names are case-insensitive')
  })

  test('specificity is recorded, and it is what RFC 9110 orders by', () => {
    const ranges = parseAccept('*/*, text/*, text/csv') as ReadonlyArray<{ specificity: number }>
    assert.deepEqual(ranges.map((r) => r.specificity), [0, 1, 2])
  })

  test('a wildcard type with a concrete subtype is not a range', () => {
    assert.equal(parseAccept('*/json'), null)
  })

  test('a comma inside a quoted parameter does not split the range', () => {
    const ranges = parseAccept('text/csv;label="a,b"') as ReadonlyArray<unknown>
    assert.equal(ranges.length, 1, 'one range, not two malformed ones')
  })

  test('ranges past the cap are ignored, and the cap is small enough to bound the work', () => {
    const many = new Array(200).fill('text/plain').join(', ')
    assert.equal((parseAccept(many) as ReadonlyArray<unknown>).length, MAX_ACCEPT_RANGES)
    assert.ok(MAX_ACCEPT_RANGES >= 8, 'a browser sends up to five; the cap must not clip a real client')
  })

  test('parameters other than q are ignored — the stated limitation', () => {
    const ranges = parseAccept('application/json;profile="urn:x";q=0.5') as ReadonlyArray<{ q: number }>
    assert.equal(ranges[0]!.q, 0.5)
    assert.equal(qualityFor(ranges as never, 'application', 'json'), 0.5)
  })
})

describe('the match (§13.4)', () => {
  const offers = offersOf([JSON_MEDIA, CSV])
  const pick = (accept: string): string | null => {
    const index = selectOffer(accept, offers)
    return index === -1 ? null : (offers[index]!.media)
  }

  test('an exact type wins', () => {
    assert.equal(pick('text/csv'), CSV)
    assert.equal(pick('application/json'), JSON_MEDIA)
  })

  test('a subtype wildcard matches within its type', () => {
    assert.equal(pick('text/*'), CSV)
    assert.equal(pick('application/*'), JSON_MEDIA)
  })

  test('a full wildcard takes the server preference — declaration order', () => {
    assert.equal(pick('*/*'), JSON_MEDIA)
    assert.equal(
      offersOf([CSV, JSON_MEDIA])[selectOffer('*/*', offersOf([CSV, JSON_MEDIA]))]!.media,
      CSV,
      'reverse the declaration and the answer reverses with it',
    )
  })

  test('quality decides between two things the client will accept', () => {
    assert.equal(pick('application/json;q=0.8, text/csv;q=0.9'), CSV)
    assert.equal(pick('application/json;q=0.9, text/csv;q=0.8'), JSON_MEDIA)
  })

  test('a tie goes to the server, not to the alphabet', () => {
    assert.equal(pick('text/csv;q=0.5, application/json;q=0.5'), JSON_MEDIA)
  })

  test('nothing acceptable is -1, and that is the 406', () => {
    assert.equal(pick('application/xml'), null)
    assert.equal(pick('image/png, application/pdf'), null)
  })

  /**
   * The case every implementation that scores by "highest q among matching
   * ranges" gets backwards — and getting it backwards means serving a
   * representation the client named and refused.
   */
  test('an explicit q=0 is honoured even under a wildcard that allows everything', () => {
    assert.equal(pick('text/csv;q=0, */*'), JSON_MEDIA, 'anything except CSV')
    assert.equal(pick('application/json;q=0, */*'), CSV)
  })

  test('q=0 on everything is a 406, not a fallback', () => {
    assert.equal(pick('*/*;q=0'), null)
    assert.equal(pick('text/csv;q=0, application/json;q=0'), null)
  })

  test('a more specific range overrides a less specific one in both directions', () => {
    assert.equal(pick('text/*;q=0, */*'), JSON_MEDIA, 'no text at all')
    assert.equal(pick('*/*;q=0, text/csv'), CSV, 'nothing, except CSV')
  })
})

describe('the cache is a cache, not a correctness surface (§13.4)', () => {
  const reps = new Map<string, Representation>([
    [JSON_MEDIA, { media: JSON_MEDIA, contentType: 'application/json; charset=utf-8', statuses: new Set([200]), writers: new Map() }],
    [CSV, { media: CSV, contentType: 'text/csv; charset=utf-8', statuses: new Set([200]), writers: new Map() }],
  ])

  test('a warm answer equals a cold one, including a cached 406', () => {
    const cold = makeNegotiator([JSON_MEDIA, CSV], reps)
    const warm = makeNegotiator([JSON_MEDIA, CSV], reps)
    for (const header of ['text/*', 'application/xml', 'text/csv;q=0, */*', '*/*;q=0']) {
      const first = cold(header)
      const second = cold(header)
      assert.equal(first, second, `${header} changed on the second call`)
      assert.equal(warm(header), first, 'a fresh negotiator agrees with a warmed one')
    }
  })

  test('eviction never changes an answer', () => {
    const negotiate = makeNegotiator([JSON_MEDIA, CSV], reps)
    const before = negotiate('text/*;q=0.4')
    for (let i = 0; i < NEGOTIATION_CACHE_LIMIT * 3; i++) negotiate(`application/x-${i};q=0.1, text/*;q=0.9`)
    assert.equal(negotiate('text/*;q=0.4'), before, 'the entry was evicted, not corrupted')
  })

  test('the cache is bounded by attacker-chosen keys', () => {
    const negotiate = makeNegotiator([JSON_MEDIA, CSV], reps)
    for (let i = 0; i < 5_000; i++) negotiate(`application/x-${i}`)
    // No accessor to the map by design; the bound is asserted through the
    // constant the implementation is required to honour, and through the
    // eviction test above proving a full map still answers correctly.
    assert.ok(NEGOTIATION_CACHE_LIMIT <= 64, 'a cache keyed on a header must stay small')
  })
})

describe('media type declarations (§13.4)', () => {
  test('a bare type/subtype is accepted and lowercased', () => {
    const parsed = normaliseMediaType('Application/JSON')
    assert.ok(!isMediaProblem(parsed))
    assert.equal((parsed as { media: string }).media, JSON_MEDIA)
  })

  test('a parameter, a wildcard and a non-media-type are each refused, distinctly', () => {
    assert.equal(normaliseMediaType('text/csv; charset=utf-8'), 'has-parameters')
    assert.equal(normaliseMediaType('*/*'), 'wildcard')
    assert.equal(normaliseMediaType('text/*'), 'wildcard')
    assert.equal(normaliseMediaType('json'), 'not-a-media-type')
    assert.equal(normaliseMediaType(''), 'not-a-media-type')
  })

  test('the JSON family is the compiled serializer, and +json is in it', () => {
    assert.equal(isJsonMedia('application/json'), true)
    assert.equal(isJsonMedia('application/vnd.acme.v2+json'), true)
    assert.equal(isJsonMedia('application/problem+json'), true)
    assert.equal(isJsonMedia('text/csv'), false)
  })

  test('the charset is appended, because a Serializer returns a string', () => {
    assert.equal(wireMediaType('text/csv'), 'text/csv; charset=utf-8')
    assert.equal(wireMediaType(JSON_MEDIA), 'application/json; charset=utf-8')
  })

  test('a variant record is told from a schema by its keys, and {} is not one', () => {
    assert.equal(isVariantRecord({ 'application/json': Rows }), true)
    assert.equal(isVariantRecord({ type: 'object', properties: {} }), false)
    assert.equal(isVariantRecord({ $ref: '#/$defs/User' }), false, "a $ref's value has slashes; its key does not")
    assert.equal(isVariantRecord(Rows), false, 'jsonSchema() is a schema')
    assert.equal(isVariantRecord({}), false, 'a typo, not a declaration of nothing')
    assert.equal(isVariantRecord({ nope: Rows }), false, 'no slash anywhere — indistinguishable from a bad schema')
    assert.equal(isVariantRecord([]), false)
    assert.equal(isVariantRecord(null), false)
  })

  /**
   * The case that argued `every` down to `any`. One typo'd key among real media
   * types is a variant record with a bad key, and saying so is the whole
   * difference between a usable diagnostic and "your schema would not convert".
   */
  test('one typo among real media types is still a variant record', () => {
    assert.equal(isVariantRecord({ 'application/json': Rows, csv: Rows }), true)
  })
})

// ─────────────────────────────────────────────────────────────────────────────

function negotiatedApp() {
  const app = makeApp()
  app.get('/rows', {
    response: { 200: { 'application/json': Rows, 'text/csv': Rows } },
  }, () => [{ id: 1, email: 'a@b.c', password: 'leaked' }] as never)
  return app
}

const get = (app: ReturnType<typeof makeApp>, path: string, accept?: string) =>
  app.inject('GET', path, accept === undefined ? {} : { headers: { accept } })

describe('end to end (§13.4)', () => {
  test('the chosen representation decides the writer and the Content-Type', async () => {
    const app = negotiatedApp()
    await app.ready()

    const json = await get(app, '/rows', JSON_MEDIA)
    assert.equal(json.header('content-type'), 'application/json; charset=utf-8')
    assert.deepEqual(json.json(), [{ id: 1, email: 'a@b.c' }])

    const csv = await get(app, '/rows', CSV)
    assert.equal(csv.header('content-type'), 'text/csv; charset=utf-8')
    assert.equal(csv.text(), 'id,email\n1,a@b.c')
  })

  /**
   * §13.3's guarantee has to survive the new dimension. It would be an easy
   * thing to lose: the negotiated path builds its serializers through a
   * different call site, and a path that forgot to compile one would fall back
   * to `JSON.stringify` and emit everything.
   */
  test('an undeclared field cannot be emitted, in either representation', async () => {
    const app = negotiatedApp()
    await app.ready()
    assert.equal((await get(app, '/rows', JSON_MEDIA)).text().includes('leaked'), false)
    assert.equal((await get(app, '/rows', CSV)).text().includes('leaked'), false)
  })

  test('no Accept header is the server preference, and it is the first declared', async () => {
    const app = negotiatedApp()
    await app.ready()
    assert.equal((await get(app, '/rows')).header('content-type'), 'application/json; charset=utf-8')
  })

  test('ctx.negotiated is set before the handler and carries the bare media type', async () => {
    const seen: Array<string | null> = []
    const app = makeApp()
    app.get('/rows', {
      response: { 200: { 'application/json': Rows, 'text/csv': Rows } },
    }, (ctx) => { seen.push(ctx.negotiated); return [] as never })
    app.get('/plain', { response: { 200: Rows } }, (ctx) => { seen.push(ctx.negotiated); return [] as never })
    await app.ready()

    await get(app, '/rows', CSV)
    await get(app, '/plain', CSV)
    assert.deepEqual(seen, ['text/csv', null], 'null means "this route has nothing to decide"')
  })

  test('an unacceptable Accept is a 406 that lists what the route can produce', async () => {
    const app = negotiatedApp()
    await app.ready()

    const res = await get(app, '/rows', 'application/xml')
    assert.equal(res.status, 406)
    const problem = res.json<{ code: string; errors: { available: string[] } }>()
    assert.equal(problem.code, Codes.NOT_ACCEPTABLE)
    assert.deepEqual(problem.errors.available, [JSON_MEDIA, CSV])
  })

  test('the 406 is an ordinary HttpError, so onError sees it', async () => {
    const seen: string[] = []
    const app = negotiatedApp()
    app.hook('onError', (_ctx, error) => { seen.push((error as { code: string }).code) })
    await app.ready()

    await get(app, '/rows', 'application/xml')
    assert.deepEqual(seen, [Codes.NOT_ACCEPTABLE])
    assert.ok(new NotAcceptable() instanceof Error)
  })

  /**
   * The `Vary: Origin` lesson (§32.2), transposed. A response with no `Vary` is
   * one a shared cache may hand to a client that asked for something else, and
   * the two requests that most need the header are the two a naive
   * implementation skips: the one that sent no `Accept`, and the one that was
   * refused.
   */
  test('Vary: Accept is present with no Accept header, and on the 406', async () => {
    const app = negotiatedApp()
    await app.ready()

    assert.equal((await get(app, '/rows')).header('vary'), 'Accept', 'no Accept header')
    assert.equal((await get(app, '/rows', CSV)).header('vary'), 'Accept')
    assert.equal((await get(app, '/rows', 'application/xml')).header('vary'), 'Accept', 'on the 406')
  })

  test('a route that is not negotiated stages no Vary and ignores Accept', async () => {
    const app = makeApp()
    app.get('/plain', { response: { 200: Rows } }, () => [{ id: 1, email: 'a@b.c' }] as never)
    await app.ready()

    const res = await get(app, '/plain', CSV)
    assert.equal(res.status, 200, 'RFC 9110 permits disregarding Accept')
    assert.equal(res.header('vary'), undefined)
    assert.equal(res.header('content-type'), 'application/json; charset=utf-8')
  })

  /**
   * §12.1's "one envelope", from the other side. A status declared in the plain
   * form is not subject to negotiation, and inheriting the negotiated
   * Content-Type would put `text/csv` on a JSON problem document — a failure
   * that looks like a client bug and is not.
   */
  test('a status declared in the plain form keeps its own Content-Type', async () => {
    const app = makeApp()
    app.get('/rows', {
      response: {
        200: { 'application/json': Rows, 'text/csv': Rows },
        404: Problem,
      },
    }, (ctx) => ctx.json({ code: 'GONE', extra: 'dropped' }, { status: 404 }) as never)
    await app.ready()

    const res = await get(app, '/rows', CSV)
    assert.equal(res.status, 404)
    assert.equal(res.header('content-type'), 'application/json; charset=utf-8', 'not text/csv')
    assert.deepEqual(res.json(), { code: 'GONE' }, 'and its own contract still filtered')
  })

  test('a staged status picks the contract egress will actually send', async () => {
    const app = makeApp()
    app.get('/rows', {
      response: {
        200: { 'application/json': Rows, 'text/csv': Rows },
        201: { 'application/json': Rows, 'text/csv': Rows },
      },
    }, (ctx) => { ctx.res.status(201); return [{ id: 7, email: 'z@z.z' }] as never })
    await app.ready()

    const res = await get(app, '/rows', CSV)
    assert.equal(res.status, 201)
    assert.equal(res.text(), 'id,email\n7,z@z.z')
  })

  test('an explicit reply media wins — the handler is the authority it declared', async () => {
    const app = makeApp()
    app.get('/rows', {
      response: { 200: { 'application/json': Rows, 'text/csv': Rows } },
    }, (ctx) => ctx.text('raw', { media: 'text/plain; charset=utf-8' }) as never)
    await app.ready()

    const res = await get(app, '/rows', CSV)
    assert.equal(res.header('content-type'), 'text/plain; charset=utf-8')
  })

  test('HEAD negotiates and keeps the headers, with no body (RFC 9110 §9.3.2)', async () => {
    const app = negotiatedApp()
    await app.ready()

    const res = await app.inject('HEAD', '/rows', { headers: { accept: CSV } })
    assert.equal(res.status, 200)
    assert.equal(res.header('content-type'), 'text/csv; charset=utf-8')
    assert.equal(res.header('vary'), 'Accept')
    assert.equal(res.text(), '')
  })

  test('an onSerialize hook that swaps the payload keeps the representation', async () => {
    const app = negotiatedApp()
    app.hook('onSerialize', (_ctx, payload) => (payload as unknown[]).concat([{ id: 2, email: 'c@d.e' }]))
    await app.ready()

    const res = await get(app, '/rows', CSV)
    assert.equal(res.header('content-type'), 'text/csv; charset=utf-8')
    assert.equal(res.text(), 'id,email\n1,a@b.c\n2,c@d.e')
  })

  /**
   * The test above does *not* cover `replacePayload`'s handling of `media`, and
   * finding that out is what the negative-control script is for. The epilogue
   * runs `onSerialize` *before* the response contract is bound (§13.3.5), so at
   * the moment a hook swaps the payload there is no negotiated media on the
   * body yet — the assertion passed with the preservation deleted.
   *
   * It is still reachable, and through a documented surface: an `around`
   * middleware receives the Reply from `next()`, which has been through the
   * epilogue and *is* bound, and `replacePayload` is public API. So the
   * behaviour is right and the test was aimed at the wrong path. Here it is
   * aimed at the right one.
   */
  test('replacePayload keeps the negotiated media on an already-bound reply', () => {
    const bound = jsonReply([{ id: 1 }])
    ;(bound as { body: unknown }).body = {
      kind: 'json',
      value: [{ id: 1 }],
      serialize: () => 'id\n1',
      media: 'text/csv; charset=utf-8',
    }

    const swapped = replacePayload(bound, [{ id: 2 }])
    const body = swapped.body as { media?: string; serialize?: unknown }
    assert.equal(body.media, 'text/csv; charset=utf-8', 'the representation survived the swap')
    assert.notEqual(body.serialize, undefined, 'and so did the contract')
    assert.equal(encodeBody(swapped).media, 'text/csv; charset=utf-8')
  })

  test('negotiation runs before intake, so a refused request never reads a body', async () => {
    let parsed = 0
    const app = makeApp()
    app.post('/rows', {
      // A real validator: `jsonSchema()` describes without validating and
      // `ready()` refuses it on a request source (§13.3.6).
      body: shaped({ type: 'object', properties: { n: { type: 'number' } } }),
      response: { 200: { 'application/json': Rows, 'text/csv': Rows } },
    }, () => [] as never)
    app.hook('onParse', () => { parsed++ })
    await app.ready()

    const res = await app.inject('POST', '/rows', {
      headers: { accept: 'application/xml', 'content-type': JSON_MEDIA },
      body: { n: 1 },
    })
    assert.equal(res.status, 406)
    assert.equal(parsed, 0, 'the body of a request we were going to refuse was never read')
  })
})

describe('boot diagnostics (§13.4, §12.7)', () => {
  test('a media type with a parameter is refused, naming the bare type', async () => {
    const app = makeApp()
    app.get('/x', { response: { 200: { 'text/csv; charset=utf-8': Rows } } }, () => [] as never)
    await assert.rejects(app.ready(), (error: Error) => {
      assert.match(error.message, /ZEN_MEDIA_TYPE_INVALID/)
      assert.match(error.message, /"text\/csv"/, 'the fix names the type to write instead')
      return true
    })
  })

  test('a wildcard offer is refused', async () => {
    const app = makeApp()
    app.get('/x', { response: { 200: { '*/*': Rows } } }, () => [] as never)
    await assert.rejects(app.ready(), /ZEN_MEDIA_TYPE_INVALID/)
  })

  test('the same media type twice is refused, because only one could be reached', async () => {
    const app = makeApp()
    app.get('/x', { response: { 200: { 'application/json': Rows, 'Application/JSON': Rows } } }, () => [] as never)
    await assert.rejects(app.ready(), /ZEN_MEDIA_TYPE_INVALID/)
  })

  test('a media type with no encoder is refused, naming registerMediaEncoder', async () => {
    __resetMediaEncoders()
    const app = makeApp()
    app.get('/x', { response: { 200: { 'application/json': Rows, 'text/csv': Rows } } }, () => [] as never)
    await assert.rejects(app.ready(), (error: Error) => {
      assert.match(error.message, /ZEN_MEDIA_TYPE_UNSUPPORTED/)
      assert.match(error.message, /registerMediaEncoder\('text\/csv'/)
      return true
    })
  })

  test('two statuses offering different media types is refused, naming both', async () => {
    const app = makeApp()
    app.get('/x', {
      response: {
        200: { 'application/json': Rows, 'text/csv': Rows },
        201: { 'application/json': Rows },
      },
    }, () => [] as never)
    await assert.rejects(app.ready(), (error: Error) => {
      assert.match(error.message, /ZEN_NEGOTIATION_INCONSISTENT/)
      assert.match(error.message, /200/)
      assert.match(error.message, /201/)
      return true
    })
  })

  test('two statuses in a different order is refused too — order is the preference', async () => {
    const app = makeApp()
    app.get('/x', {
      response: {
        200: { 'application/json': Rows, 'text/csv': Rows },
        201: { 'text/csv': Rows, 'application/json': Rows },
      },
    }, () => [] as never)
    await assert.rejects(app.ready(), /ZEN_NEGOTIATION_INCONSISTENT/)
  })

  test('an encoder that refuses a schema at boot is a diagnostic, not a crash', async () => {
    __resetMediaEncoders()
    registerMediaEncoder(CSV, () => { throw new Error('rows only') })
    const app = makeApp()
    app.get('/x', { response: { 200: { 'application/json': Rows, 'text/csv': Rows } } }, () => [] as never)
    await assert.rejects(app.ready(), (error: Error) => {
      assert.match(error.message, /ZEN_MEDIA_TYPE_UNSUPPORTED/)
      assert.match(error.message, /rows only/, "the encoder's own message survives")
      return true
    })
  })

  test('a typo alongside real media types names the typo, not the schema', async () => {
    const app = makeApp()
    app.get('/x', { response: { 200: { 'application/json': Rows, csv: Rows } } }, () => [] as never)
    await assert.rejects(app.ready(), (error: Error) => {
      assert.match(error.message, /ZEN_MEDIA_TYPE_INVALID/)
      assert.match(error.message, /"csv", which is not a media type/)
      assert.match(error.message, /type\/subtype/, 'the fix shows the shape to write')
      return true
    })
  })

  test('the diagnostics aggregate — three bad routes is one boot, not three', async () => {
    const app = makeApp()
    app.get('/a', { response: { 200: { 'application/json': Rows, nope: Rows } } }, () => [] as never)
    app.get('/b', { response: { 200: { 'also/*': Rows } } }, () => [] as never)
    app.get('/c', { response: { 200: { 'text/csv; q=1': Rows } } }, () => [] as never)
    await assert.rejects(app.ready(), (error: Error) => {
      for (const path of ['/a', '/b', '/c']) {
        assert.match(error.message, new RegExp(path), `${path} was not reported in the same run`)
      }
      return true
    })
  })

  test('a route with one media type in the variant form is legal, and is negotiated', async () => {
    const app = makeApp()
    app.get('/strict', { response: { 200: { 'application/json': Rows } } }, () => [] as never)
    await app.ready()

    assert.equal((await get(app, '/strict', CSV)).status, 406, 'the variant form is the opt-in to strictness')
    assert.equal((await get(app, '/strict', JSON_MEDIA)).status, 200)
    assert.equal((await get(app, '/strict')).header('vary'), 'Accept')
  })
})

describe('the graph is the one description (§2.4)', () => {
  test('RouteRecord.negotiation carries the offers in preference order', async () => {
    const app = negotiatedApp()
    await app.ready()

    const record = app.graph().routes.find((r) => r.path === '/rows')!
    assert.deepEqual(record.negotiation?.offers, [JSON_MEDIA, CSV])
    assert.deepEqual(record.negotiation?.statuses, [200])
  })

  test('a route that is not negotiated has a null record', async () => {
    const app = makeApp()
    app.get('/plain', { response: { 200: Rows } }, () => [] as never)
    await app.ready()
    assert.equal(app.graph().routes[0]!.negotiation, null)
  })

  test('explainRoute puts negotiation where it runs, and prints the offers', async () => {
    const app = negotiatedApp()
    await app.ready()

    const printed = explainRoute(app.graph().routes.find((r) => r.path === '/rows')!)
    assert.match(printed, /negotiate/)
    assert.match(printed, /application\/json > text\/csv/, 'preference order, not a set')
    assert.match(printed, /200×2 \(compiled\)/, 'one contract per representation')
    assert.ok(
      printed.indexOf('negotiate') < printed.indexOf('handler'),
      'the chain must show that a 406 precedes the handler',
    )
  })
})

describe('zero cost when it is not used (§9.4)', () => {
  /**
   * The pipeline unit for one route, and *only* the pipeline unit.
   *
   * `find(u => u.name.includes('/plain'))` is what the first draft of this
   * suite used, and it was wrong in the way §20.7 warns about: response
   * serializers are compiled before pipelines and are named
   * `GET /plain#200`, so the search matched a serializer and every assertion
   * below passed without ever looking at a pipeline. The count assertion in the
   * last test is what caught it — it expected one `d.negotiate(ctx)` and found
   * zero in a unit that could not have contained one.
   */
  const pipelineOf = (app: ReturnType<typeof makeApp>, method: string, path: string): string => {
    const unit = app.generatedSource().find((u) => u.name === `pipeline:${method}_${path}`)
    assert.ok(unit !== undefined, `no pipeline unit for ${method} ${path}`)
    return unit.source
  }

  /**
   * The house gate, against the generated bytes rather than a clock. A route
   * that declares one representation must compile to exactly what it compiled
   * before this feature existed — no `Accept` read, no `Vary`, no branch.
   */
  test('a plain route emits a pipeline byte-identical to one in an app with no negotiation', async () => {
    const source = async (declare: boolean): Promise<string> => {
      const app = makeApp()
      app.get('/plain', { response: { 200: Rows } }, () => [] as never)
      if (declare) {
        app.get('/rows', { response: { 200: { 'application/json': Rows, 'text/csv': Rows } } }, () => [] as never)
      }
      await app.ready()
      return pipelineOf(app, 'GET', '/plain')
    }

    assert.equal(await source(false), await source(true))
  })

  test('and its emitted text mentions neither negotiation nor the negotiated binding', async () => {
    const app = makeApp()
    app.get('/plain', { response: { 200: Rows } }, () => [] as never)
    await app.ready()

    const emitted = pipelineOf(app, 'GET', '/plain')
    assert.equal(emitted.includes('negotiate'), false)
    assert.equal(emitted.includes('attachNegotiated'), false)
    assert.match(emitted, /attachSerializer/, 'it still binds the plain contract')
  })

  test('a route with no response schema at all is untouched too', async () => {
    const app = makeApp()
    app.get('/bare', () => ({ ok: true }))
    await app.ready()

    const emitted = pipelineOf(app, 'GET', '/bare')
    assert.equal(emitted.includes('negotiate'), false)
    assert.equal(emitted.includes('Serializer'), false)
  })

  test('a negotiated route emits exactly one negotiation call', async () => {
    const app = negotiatedApp()
    await app.ready()

    const emitted = pipelineOf(app, 'GET', '/rows')
    assert.equal(emitted.split('d.negotiate(ctx)').length - 1, 1)
    assert.match(emitted, /attachNegotiated/)
    assert.equal(emitted.includes('attachSerializer'), false, 'one binding, not both')
  })
})
