/**
 * Coercion profiles — rfcs/0001 §11.4.
 *
 * Query strings, path params, headers and cookies are **always strings on the
 * wire**. `?page=2` has no way to say "the number two"; it can only say the
 * character `2`. Every framework deals with this badly in a different way:
 * Express hands you the string and lets it reach your database as `'2'`, Fastify
 * coerces everything JSON Schema says to coerce, and the Zod-with-Express
 * pattern makes you write `z.coerce.number()` on every field of every query
 * schema forever.
 *
 * Zen's position is that the *schema already contains the answer*. A field
 * declared `z.number()` wants a number; a field declared `z.string()` wants the
 * string it was given. So coercion here is **schema-guided**: the request
 * source's schema is converted to JSON Schema once at boot, and a coercion plan
 * is derived from the types it declares (§11.4, and see `compile/coercion.ts`).
 *
 * The three rules that fall out of that, and that everything else in this
 * subsystem is downstream of:
 *
 *   1. **A position that accepts a string is never coerced.** `?zip=01234`
 *      against `z.string()` stays `'01234'`, and against a
 *      `z.union([z.string(), z.number()])` it stays a string too, because the
 *      value it arrived as is already one the schema accepts. This is the rule
 *      that makes blanket coercion — the thing every framework that guesses
 *      gets wrong — impossible here.
 *   2. **Coercion cannot fail.** A value it will not convert is passed through
 *      *unchanged* so the schema rejects it with the schema's own message.
 *      There is exactly one authority on whether a request is valid, and it is
 *      not this file.
 *   3. **A source with nothing to coerce emits no code.** Same rule as hooks
 *      (§9.4) and deadlines (§4.4), asserted the same way — against the
 *      generated bytes, in CI.
 *
 * JSON bodies get **no coercion by default** because JSON has real types:
 * coercing there would mean `{"age":"42"}` silently satisfying an `age: number`
 * schema, which hides a client bug rather than reporting it. Form bodies are
 * the same wire format as a query string and have the same problem, which is
 * why the profile is per-source and settable rather than fixed.
 */

/** The five request sources a route can declare a schema for — §4.2 stage 7. */
export type ValidationSource = 'params' | 'query' | 'headers' | 'cookies' | 'body'

/** Validated in this order: cheap, small, already-in-memory sources first. */
export const VALIDATION_SOURCES: readonly ValidationSource[] =
  Object.freeze(['params', 'query', 'headers', 'cookies', 'body'] as const)

/**
 * Which spellings of a boolean the wire is allowed to use.
 *
 * Configurable because the answer is genuinely different per protocol and there
 * is no defensible universal set: an HTML checkbox submits `on`, a shell script
 * writes `1`, a human writes `yes`, and a JSON-ish client writes `true`. All
 * four are in the default set; comparison is case-insensitive. Anything outside
 * both lists is left alone for the schema to reject (rule 2 above).
 */
export interface BooleanWords {
  readonly true: readonly string[]
  readonly false: readonly string[]
}

export const BOOLEAN_WORDS: BooleanWords = Object.freeze({
  true: Object.freeze(['true', '1', 'yes', 'on']) as readonly string[],
  false: Object.freeze(['false', '0', 'no', 'off']) as readonly string[],
})

/**
 * How a repeated or multi-valued parameter reaches the server.
 *
 *   - `repeat`   — `?a=1&a=2`. The web's default, and what `parseQuery` already
 *                  produces. Its one sharp edge is that `?a=1` alone is a
 *                  *string*, not a one-element array, which is the single most
 *                  common query-parsing bug in every language. Where the schema
 *                  declares an array, this wraps it.
 *   - `comma`    — `?a=1,2`, and the default for headers, where RFC 9110 list
 *                  syntax says exactly this. Optional whitespace after the
 *                  comma is trimmed, as the grammar allows.
 *   - `bracket`  — `?a[]=1&a[]=2`, the PHP/Rails spelling. Read as an alternate
 *                  key, so a schema field `a` also collects `a[]`.
 *   - `none`     — no array handling; the value arrives as parsed.
 *
 * This is *not* `qs`-style deep parsing. `nested` is a separate switch and is
 * off everywhere by default (§19.5).
 */
export type ArrayStyle = 'repeat' | 'bracket' | 'comma' | 'none'

export interface CoercionProfile {
  /** `"42"` → `42`, where the schema declares `number` or `integer`. */
  readonly numbers: boolean
  /** `"true"` → `true`, where the schema declares `boolean`. */
  readonly booleans: boolean | BooleanWords
  /**
   * ISO string → `Date`.
   *
   * **Not implemented, and false everywhere.** Kept in the profile because the
   * gap is worth naming rather than hiding: no shape language can express "this
   * position wants a `Date`". A schema whose *output* is a `Date` is precisely
   * the schema JSON Schema cannot describe — `z.toJSONSchema(z.date())` throws
   * `Date cannot be represented in JSON Schema` — so a date coercion could only
   * be applied by guessing at `format: 'date-time'`, which is the one case
   * where the validator provably wants a **string** and coercing would break a
   * schema that works today. `z.coerce.date()` covers it in one call and is
   * checked by the library that owns the type. See §28.8.
   */
  readonly dates: boolean
  readonly arrays: ArrayStyle
  /**
   * `?q=` → the field is absent rather than `''`.
   *
   * Off everywhere by default, and deliberately so. An empty parameter is
   * information: it is the difference between "the client searched for nothing"
   * and "the client did not search", and those two produce different validation
   * errors and different `.default()` outcomes. HTML forms submit empty inputs
   * for every untouched field, so an app whose bodies come from forms usually
   * wants this on for `body`; nothing else should have to.
   */
  readonly emptyStringAsUndefined: boolean
  /**
   * `?a[b]=1` → `{ a: { b: 1 } }`.
   *
   * **Not implemented, and off everywhere.** `qs`-style deep parsing is a
   * prototype-pollution and algorithmic-complexity surface (§19.5) and almost
   * nobody needs it. Present so that the answer to "can Zen do this?" is a
   * documented no rather than an absence.
   */
  readonly nested: boolean
}

/**
 * The defaults, chosen to match what each wire format actually implies —
 * §11.4's table.
 *
 * `params` gets numbers but not booleans because `/users/:id` is a number often
 * and a boolean essentially never, and because a path segment reading `true`
 * is far more likely to be a slug. `headers` gets only list-splitting because a
 * header's value is a string by RFC and a numeric-looking one (`x-retry: 007`)
 * is usually an opaque token. `cookies` gets nothing at all: a cookie is a
 * bearer of opaque values and coercing one is how a session id becomes a
 * float. `body` gets nothing because JSON has real types — see the header of
 * this file.
 */
export const COERCION_DEFAULTS: Readonly<Record<ValidationSource, CoercionProfile>> = Object.freeze({
  params: Object.freeze({ numbers: true, booleans: false, dates: false, arrays: 'none', emptyStringAsUndefined: false, nested: false }),
  query: Object.freeze({ numbers: true, booleans: true, dates: false, arrays: 'repeat', emptyStringAsUndefined: false, nested: false }),
  headers: Object.freeze({ numbers: false, booleans: false, dates: false, arrays: 'comma', emptyStringAsUndefined: false, nested: false }),
  cookies: Object.freeze({ numbers: false, booleans: false, dates: false, arrays: 'none', emptyStringAsUndefined: false, nested: false }),
  body: Object.freeze({ numbers: false, booleans: false, dates: false, arrays: 'none', emptyStringAsUndefined: false, nested: false }),
}) as Readonly<Record<ValidationSource, CoercionProfile>>

/** Every switch off. What `coercion: false` resolves to, at any scope. */
export const COERCION_OFF: CoercionProfile = Object.freeze({
  numbers: false,
  booleans: false,
  dates: false,
  arrays: 'none',
  emptyStringAsUndefined: false,
  nested: false,
})

/**
 * What an app, a collection or a route may declare.
 *
 * `false` — at any level — means "nothing below here is coerced", and an inner
 * scope can turn it back on. Per-source, `false` is the same thing for that one
 * source. Anything else is a *partial*: profiles merge field by field down the
 * chain, unlike deadlines, where the innermost declaration wins outright
 * (§4.4). The difference is not an inconsistency — a profile is six independent
 * switches and two budgets are one value, so "the nearest one wins" is the
 * right rule for a deadline and the wrong rule for this.
 */
export type CoercionSpec = false | CoercionOptions

export interface CoercionOptions {
  readonly params?: Partial<CoercionProfile> | false | undefined
  readonly query?: Partial<CoercionProfile> | false | undefined
  readonly headers?: Partial<CoercionProfile> | false | undefined
  readonly cookies?: Partial<CoercionProfile> | false | undefined
  readonly body?: Partial<CoercionProfile> | false | undefined
}

// ─────────────────────────────────────────────────────────────────────────────
// The plan — what the compiler emits from, and what every reader reads
// ─────────────────────────────────────────────────────────────────────────────

/**
 * One conversion, chosen at boot from the schema's declared type.
 *
 * A closed set of five, on purpose. The temptation in a subsystem like this is
 * an extensible converter registry; the reason there isn't one is that every
 * entry here has to be something the *schema language* can ask for, and a
 * user-defined coercion has no way to be requested — the schema would have to
 * declare a type JSON Schema does not have. A schema that needs a bespoke
 * conversion already has the tool for it: `z.transform`, which runs inside the
 * validator where its failure has somewhere to go.
 */
export type CoerceOp =
  /** Strict decimal grammar → `number`; anything else passes through. */
  | { readonly kind: 'number' }
  /** As `number`, but refuses to silently lose precision — see `coerceInteger`. */
  | { readonly kind: 'integer' }
  | { readonly kind: 'boolean'; readonly words: BooleanWords }
  | {
      readonly kind: 'array'
      /** `?a=1` where an array is declared → `['1']`. */
      readonly wrap: boolean
      /** Split a single string on this separator first (`comma` style). */
      readonly split: string | null
      /** Applied to every element, or `null` when the element type is a string. */
      readonly items: CoerceOp | null
    }

export interface CoerceField {
  readonly key: string
  /**
   * The alternate key this field also collects, for `bracket` style: a field
   * named `tags` reads `tags[]` when `tags` is absent.
   */
  readonly altKey: string | null
  /** `''` → absent, applied before `op`. Separate so `op` can stay a pure map. */
  readonly emptyToUndefined: boolean
  readonly op: CoerceOp | null
}

/**
 * One source's plan. Never empty — an empty plan is `null`, so that "this route
 * coerces nothing" is representable only one way and the zero-cost check is a
 * null test rather than a length test.
 */
export interface CoercePlan {
  readonly source: ValidationSource
  readonly fields: readonly CoerceField[]
}

/**
 * What the route record carries, and what `explainRoute`, the OpenAPI generator
 * and the pipeline compiler all read — §2.4.
 *
 * On the record rather than inside the compiler for the same reason `hooks` and
 * `timeout` are: it is a function of static registration, so putting it in one
 * place is what stops the document, the explanation and the running code from
 * disagreeing about whether `?tags=a` is one string or a one-element array.
 */
export type CoercionRecord = ReadonlyMap<ValidationSource, CoercePlan>
